/**
 * Lead Safety Tab — Cincinnati Civic Data Platform
 *
 * Shows GCWW lead service line inventory by neighborhood, replacement program
 * activity, and actionable guidance for residents in affected areas.
 *
 * Data sources:
 *   - /data/lead_service_lines.json   — pre-built neighborhood inventory
 *     (generated by scripts/build_lead.py from GCWW open data)
 *   - Cincinnati Open Data `b4xq-u3su` — live GCWW replacement records
 *
 * Why this matters:
 *   - 33,449 lead or unknown service lines remain in Cincinnati
 *   - ~220 children are diagnosed with elevated blood lead levels each year
 *   - Only 36.8% of children under 6 are tested
 *   - No publicly accessible civic map existed before this tab
 *
 * The tab gracefully handles the pre-built file being absent ({}) by showing
 * a build notice instead of an error, and still shows live replacement activity.
 */

import { useState, useEffect, useMemo } from 'react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell } from 'recharts';
import {
  fetchNeighborhoodLeadStats,
  fetchLeadReplacements,
  searchLeadByAddress,
  stripNeighborhoodName,
} from '../../utils/api';
import type { LeadReplacementRecord } from '../../utils/api';
import type { NeighborhoodLeadStats } from '../../types';
import { DataCard } from '../../components/ui';
import { C } from '../../components/ui/DesignAtoms';

// ── Neighborhood list ─────────────────────────────────────────────────────────

const NEIGHBORHOODS = [
  'Avondale', 'Bond Hill', 'California', 'Camp Washington', 'Carthage',
  'CBD / Riverfront', 'Clifton', 'Clifton Heights', 'College Hill',
  'Columbia-Tusculum', 'Corryville', 'East End', 'East Price Hill',
  'East Walnut Hills', 'East Westwood', 'English Woods', 'Evanston',
  'Fairview', 'Fay Apartments', 'Hartwell', 'Hyde Park', 'Kennedy Heights',
  'Linwood', 'Lower Price Hill', 'Madisonville', 'Millvale', 'Mount Adams',
  'Mount Airy', 'Mount Auburn', 'Mt. Lookout', 'Mt. Washington',
  'North Avondale', 'North Fairmount', 'Northside', 'Oakley', "O'Bryonville",
  'Over-the-Rhine', 'Paddock Hills', 'Pendleton', 'Pleasant Ridge', 'Queensgate',
  'Riverside', 'Roselawn', 'Sayler Park', 'Sedamsville', 'South Cumminsville',
  'South Fairmount', 'Spring Grove Village', 'Walnut Hills', 'West End',
  'West Price Hill', 'Westwood', 'Winton Hills',
];

// ── Helpers ───────────────────────────────────────────────────────────────────

function pct(numerator: number, denominator: number): string {
  if (!denominator) return 'N/A';
  return `${Math.round((numerator / denominator) * 100)}%`;
}

function riskStyle(leadOrUnknown: number, total: number): React.CSSProperties {
  if (!total) return { color: C.muted, background: C.limestone, border: `1px solid ${C.rule}` };
  const rate = leadOrUnknown / total;
  if (rate > 0.5) return { color: C.brick, background: C.brickLight, border: `1px solid ${C.brick}` };
  if (rate > 0.25) return { color: C.ochre, background: 'rgba(200,134,26,0.1)', border: `1px solid ${C.ochre}` };
  if (rate > 0.1) return { color: '#8a6e3e', background: 'rgba(200,134,26,0.07)', border: `1px solid ${C.ochre}` };
  return { color: C.hill, background: C.hillLight, border: `1px solid ${C.hill}` };
}

function riskLabel(leadOrUnknown: number, total: number): string {
  if (!total) return 'No Data';
  const rate = leadOrUnknown / total;
  if (rate > 0.5) return 'High Risk';
  if (rate > 0.25) return 'Elevated Risk';
  if (rate > 0.1) return 'Moderate Risk';
  return 'Lower Risk';
}

// ── Sub-components ────────────────────────────────────────────────────────────

/** Stat row used in the inventory breakdown */
function StatRow({
  label,
  value,
  barWidth,
  barColor,
  note,
}: {
  label: string;
  value: number | string;
  barWidth?: number; // 0–100 for visual bar
  barColor?: string;
  note?: string;
}) {
  return (
    <div className="py-2 last:border-0" style={{ borderBottom: `1px solid ${C.rule}` }}>
      <div className="flex justify-between items-center">
        <div>
          <span className="text-[13px]" style={{ color: C.ink }}>{label}</span>
          {note && <p className="text-[11px] mt-0.5" style={{ color: C.muted }}>{note}</p>}
        </div>
        <span className="text-[13px] font-semibold ml-4 shrink-0" style={{ color: C.river }}>
          {typeof value === 'number' ? value.toLocaleString() : value}
        </span>
      </div>
      {barWidth !== undefined && (
        <div className="mt-1.5 h-1.5 rounded-full overflow-hidden" style={{ background: C.limestone }}>
          <div
            className="h-full rounded-full transition-all duration-500"
            style={{ width: `${Math.min(barWidth, 100)}%`, background: barColor ?? C.river }}
          />
        </div>
      )}
    </div>
  );
}

/** Urgency header with city-wide lead crisis stats */
function UrgencyBanner() {
  return (
    <div className="page-paper rounded-md p-6 mb-2" style={{ borderLeft: `4px solid ${C.brick}` }}>
      <div className="text-[10px] font-bold uppercase tracking-widest mb-1" style={{ color: C.brick }}>Lead Safety Alert</div>
      <div className="serif mb-3" style={{ fontSize: 22, fontWeight: 500, color: C.ink, lineHeight: 1.2 }}>
        Lead-free water isn't guaranteed for every household in Cincinnati.
      </div>
      <p className="text-[13px] leading-relaxed mb-5" style={{ color: C.muted, maxWidth: 680 }}>
        Thousands of service lines — the pipes connecting the city main to your home — are still
        lead or unidentified material. Only 36.8% of children under 6 are tested for lead exposure.
      </p>
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {[
          { value: '33,449', label: 'Lead or unknown lines', sub: 'As of 2024' },
          { value: '~220', label: 'Children elevated blood lead yearly', sub: 'City of Cincinnati' },
          { value: '36.8%', label: 'Children under 6 who are tested', sub: 'Far below national avg' },
          { value: '$0', label: 'Cost for full replacement', sub: 'When your area is selected' },
        ].map(({ value, label, sub }) => (
          <div key={label} className="rounded-md p-3" style={{ background: C.limestone, border: `1px solid ${C.rule}` }}>
            <div className="serif font-medium leading-none" style={{ fontSize: 28, color: C.brick }}>{value}</div>
            <div className="text-[11px] mt-1.5" style={{ color: C.ink }}>{label}</div>
            <div className="text-[10px] mt-0.5" style={{ color: C.muted }}>{sub}</div>
          </div>
        ))}
      </div>
    </div>
  );
}

/**
 * Replacement Program Status card — loaded from pre-built JSON.
 *
 * IMPORTANT: The underlying dataset (b4xq-u3su) records ~6,400 service lines
 * that GCWW has formally evaluated and enrolled in the replacement program.
 * It is NOT the full city-wide inventory of all ~33,449 lead/unknown lines.
 * Lines outside the program do not appear here. This scope is disclosed in the UI.
 *
 * Material codes: PB = lead, CU = copper, GS = galvanized, LDNR = lead-do-not-replace.
 * "replaced" specifically means: a lead (PB/LDNR) line with status='Complete'.
 * Copper lines with 'Complete' status count under 'copper', not 'replaced'.
 */
function InventoryCard({ neighborhood }: { neighborhood: string }) {
  const [stats, setStats] = useState<NeighborhoodLeadStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [notBuilt, setNotBuilt] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setLoading(true);
    setStats(null);
    setError(null);
    setNotBuilt(false);

    fetchNeighborhoodLeadStats()
      .then((map) => {
        if (map.size === 0) {
          setNotBuilt(true);
          return;
        }
        const key = stripNeighborhoodName(neighborhood);
        const found = map.get(key) ?? null;
        setStats(found);
      })
      .catch((e) => setError(String(e)))
      .finally(() => setLoading(false));
  }, [neighborhood]);

  if (notBuilt) {
    return (
      <DataCard
        title="Service Line Inventory"
        loading={false}
        error={null}
        attribution={{ datasetName: 'GCWW Lead Service Line Inventory', lastUpdated: null }}
      >
        <div className="rounded-md p-4 text-[13px] space-y-2" style={{ background: 'rgba(200,134,26,0.08)', border: `1px solid ${C.ochre}`, color: C.ink }}>
          <p className="font-semibold" style={{ color: C.ochre }}>⚙️ Pre-computed data not yet generated</p>
          <p>
            The full service line inventory requires a one-time build step. Run this command
            in the project directory to generate the data:
          </p>
          <pre className="rounded p-2 text-[11px] font-mono overflow-x-auto" style={{ background: C.limestone }}>
            python3 scripts/build_lead.py
          </pre>
          <p>
            Once generated, <code className="text-xs bg-amber-100 px-1 rounded">public/data/lead_service_lines.json</code> will
            populate this section with lead/unknown/copper counts for all 52 neighborhoods.
          </p>
          <p>
            In the meantime, the <strong>Replacement Activity</strong> card below shows live data
            from Cincinnati's open data portal.
          </p>
        </div>
      </DataCard>
    );
  }

  const leadOrUnknown = stats ? stats.lead + stats.unknown : 0;

  return (
    <DataCard
      title="Replacement Program Status"
      loading={loading}
      error={error}
      attribution={{ datasetName: 'GCWW Lead Service Line Replacement Program', lastUpdated: stats?.asOf ?? null, uid: 'b4xq-u3su' }}
    >
      {stats === null && !loading ? (
        <p className="text-[13px]" style={{ color: C.muted }}>
          No program data found for {neighborhood} — this neighborhood may not yet have
          lines enrolled in GCWW's formal replacement program.
        </p>
      ) : stats ? (
        <div className="space-y-2">
          {/* Scope caveat — always visible */}
          <div className="rounded-md px-3 py-2 text-[12px] mb-3" style={{ background: C.riverLight, borderLeft: `3px solid ${C.river}`, color: C.ink }}>
            <strong>Scope:</strong> This shows {neighborhood}'s {stats.total.toLocaleString()} service lines
            enrolled in GCWW's replacement program — not all lines in the neighborhood.
            Cincinnati's full inventory of ~33,449 lead/unknown lines is not available
            on the public open data portal.
          </div>

          {/* Risk badge — only meaningful if there are active lead lines */}
          {stats.lead + stats.unknown > 0 && (
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-[13px] font-semibold mb-2"
              style={riskStyle(leadOrUnknown, stats.total)}>
              <span>{riskLabel(leadOrUnknown, stats.total)}</span>
              <span className="font-normal opacity-75">·</span>
              <span>{pct(leadOrUnknown, stats.total)} of program lines still active lead</span>
            </div>
          )}

          {/* Breakdown */}
          <StatRow
            label="Active lead lines (pending replacement)"
            value={stats.lead}
            barWidth={stats.total ? (stats.lead / stats.total) * 100 : 0}
            barColor={C.brick}
            note="PB material + not yet replaced — enrolled in program, awaiting action"
          />
          <StatRow
            label="Unknown material"
            value={stats.unknown}
            barWidth={stats.total ? (stats.unknown / stats.total) * 100 : 0}
            barColor={C.ochre}
            note="No material code recorded — treated as potentially lead"
          />
          <StatRow
            label="Galvanized steel"
            value={stats.galvanized}
            barWidth={stats.total ? (stats.galvanized / stats.total) * 100 : 0}
            barColor="#8a6e3e"
            note="Corrosion concern; often co-located with lead connections"
          />
          <StatRow
            label="Copper / confirmed safe"
            value={stats.copper}
            barWidth={stats.total ? (stats.copper / stats.total) * 100 : 0}
            barColor={C.hill}
            note="CU, brass, or other non-lead material — confirmed by GCWW inspection"
          />
          <StatRow
            label="Lead lines successfully replaced"
            value={stats.replaced}
            barWidth={stats.total ? (stats.replaced / stats.total) * 100 : 0}
            barColor={C.river}
            note="PB lines with status='Complete' — lead is gone from these addresses"
          />
          <div className="pt-2 flex justify-between items-center" style={{ borderTop: `1px solid ${C.rule}` }}>
            <span className="text-[12px]" style={{ color: C.muted }}>Lines in program (this neighborhood)</span>
            <span className="text-[13px] font-bold" style={{ color: C.river }}>{stats.total.toLocaleString()}</span>
          </div>
        </div>
      ) : null}
    </DataCard>
  );
}

/** Replacement Activity card — live SODA data from ntfu-vnkd */
function ReplacementActivityCard({ neighborhood }: { neighborhood: string }) {
  const [records, setRecords] = useState<LeadReplacementRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setLoading(true);
    setError(null);
    fetchLeadReplacements(neighborhood)
      .then(setRecords)
      .catch((e) => setError(String(e)))
      .finally(() => setLoading(false));
  }, [neighborhood]);

  // Group by year for chart — use confirmed field publicreplacedate
  const yearData = useMemo(() => {
    const counts: Record<string, number> = {};
    for (const r of records) {
      const raw = r.publicreplacedate ?? '';
      const year = raw.slice(0, 4);
      if (/^\d{4}$/.test(year)) {
        counts[year] = (counts[year] ?? 0) + 1;
      }
    }
    return Object.entries(counts)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([year, count]) => ({ year, count }));
  }, [records]);

  const total = records.length;

  return (
    <DataCard
      title="Replacement Program Activity"
      loading={loading}
      error={error}
      attribution={{
        datasetName: 'GCWW Private-Side Lead Service Line Replacements',
        lastUpdated: null,
        uid: 'b4xq-u3su',
      }}
    >
      {total === 0 && !loading ? (
        <div className="space-y-1 text-[13px]" style={{ color: C.muted }}>
          <p>No replacement records with a completion date found for {neighborhood}.</p>
          <p className="text-[11px]">
            This may mean no public-side replacements have been recorded for this neighborhood yet,
            or the neighborhood name in the <code>adminarea</code> field doesn't match exactly.
            Try viewing the full dataset at{' '}
            <a href="https://data.cincinnati-oh.gov/dataset/GCWW-Private-Side-One-off-Lead-Service-Line-Replac/b4xq-u3su"
              target="_blank" rel="noopener noreferrer" className="underline" style={{ color: C.river }}>
              data.cincinnati-oh.gov
            </a>{' '}
            to verify the adminarea name format.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          <div className="rounded-md px-4 py-3 flex items-center justify-between" style={{ background: C.riverLight, border: `1px solid ${C.river}` }}>
            <div>
              <div className="serif font-medium leading-none" style={{ fontSize: 36, color: C.river }}>{total.toLocaleString()}</div>
              <div className="text-[13px] mt-1" style={{ color: C.muted }}>Private-side replacements recorded</div>
            </div>
            <div className="text-right text-[11px]" style={{ color: C.muted }}>
              <p>Private-side replacements</p>
              <p>completed through GCWW's</p>
              <p>replacement program</p>
            </div>
          </div>

          {yearData.length > 0 && (
            <div>
              <p className="text-[11px] mb-2" style={{ color: C.muted }}>Replacements by year</p>
              <ResponsiveContainer width="100%" height={140}>
                <BarChart data={yearData} margin={{ top: 4, right: 4, bottom: 4, left: 0 }}>
                  <XAxis dataKey="year" tick={{ fontSize: 11, fill: C.muted }} />
                  <YAxis tick={{ fontSize: 11, fill: C.muted }} width={30} />
                  <Tooltip
                    formatter={(v: number) => [v, 'Replacements']}
                    contentStyle={{ fontSize: '12px', borderColor: C.rule, borderRadius: 6 }}
                  />
                  <Bar dataKey="count" radius={[2, 2, 0, 0]}>
                    {yearData.map((_, i) => (
                      <Cell
                        key={i}
                        fill={C.river}
                        opacity={i === yearData.length - 1 ? 0.55 : 1}
                      />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
              <p className="text-[11px] mt-1" style={{ color: C.muted }}>Most recent year highlighted.</p>
            </div>
          )}

          <p className="text-[11px]" style={{ color: C.muted }}>
            Note: "Private-side" means the pipe from the curb to your home. The city-side
            (main to curb) replacement is handled separately and is not in this dataset.
          </p>
        </div>
      )}
    </DataCard>
  );
}

/** What to do if you're in a lead-risk neighborhood */
function ActionCard() {
  return (
    <DataCard
      title="What You Can Do"
      loading={false}
      error={null}
    >
      <div className="space-y-4 text-[13px]" style={{ color: C.ink }}>
        {/* Check your address */}
        <div className="flex gap-3">
          <span className="text-xl shrink-0">🔍</span>
          <div>
            <p className="font-semibold">Look up your specific address</p>
            <p className="mt-0.5" style={{ color: C.muted }}>
              GCWW's Lead Line Lookup shows the status of the public-side line for your address.{' '}
              <a href="https://la.mygcww.org/lead/" target="_blank" rel="noopener noreferrer" className="underline" style={{ color: C.river }}>
                Search your address at la.mygcww.org/lead
              </a>
              . For the private-side (inside your property), you or your plumber would need to
              identify the pipe material.
            </p>
          </div>
        </div>

        {/* Test your water */}
        <div className="flex gap-3">
          <span className="text-xl shrink-0">🧪</span>
          <div>
            <p className="font-semibold">Get your water tested</p>
            <p className="mt-0.5" style={{ color: C.muted }}>
              Even if your service line is listed as copper, older interior plumbing and
              solder joints can leach lead. GCWW offers{' '}
              <a href="https://la.mygcww.org/lead/" target="_blank" rel="noopener noreferrer" className="underline" style={{ color: C.river }}>
                free lead water testing kits
              </a>{' '}
              for Cincinnati customers.
            </p>
          </div>
        </div>

        {/* Replacement program */}
        <div className="flex gap-3">
          <span className="text-xl shrink-0">🔧</span>
          <div>
            <p className="font-semibold">How the replacement program works — and what it doesn't cover</p>
            <p className="mt-0.5" style={{ color: C.muted }}>
              GCWW's program replaces both the public-side (main to curb) and private-side
              (curb to your building) service line at <strong style={{ color: C.ink }}>no cost to the homeowner</strong>.
              However, <strong style={{ color: C.ink }}>you cannot request replacement on demand</strong> — the program
              operates in concentrated project areas. GCWW notifies households when their
              neighborhood is scheduled, then prioritizes homes with children under 6, pregnant
              residents, and older housing stock within that area.
            </p>
            <p className="mt-2" style={{ color: C.muted }}>
              <strong style={{ color: C.ink }}>Important:</strong> The replacement program covers the service line only.
              Lead from <strong style={{ color: C.ink }}>interior plumbing, solder joints, and fixtures inside your home</strong>{' '}
              is a separate and common exposure source. If your home was built before 1986, interior
              pipes and solder may contain lead regardless of your service line status.
            </p>
            <p className="mt-2" style={{ color: C.muted }}>
              Contact{' '}
              <a href="https://la.mygcww.org/lead/" target="_blank" rel="noopener noreferrer" className="underline" style={{ color: C.river }}>
                GCWW's lead program
              </a>{' '}
              or call <strong>513-591-7700</strong> to find out when your neighborhood is scheduled.
            </p>
          </div>
        </div>

        {/* Protect your family in the meantime */}
        <div className="flex gap-3">
          <span className="text-xl shrink-0">🚰</span>
          <div>
            <p className="font-semibold">Reduce exposure while you wait</p>
            <ul className="mt-0.5 list-disc list-inside space-y-0.5" style={{ color: C.muted }}>
              <li>Run cold water for 1–2 minutes before drinking or cooking if pipes have sat unused</li>
              <li>Use cold (never hot) water for drinking and cooking — hot water leaches more lead</li>
              <li>Use an NSF-certified lead filter (pitcher or faucet-mount)</li>
              <li>Never give young children water from the hot tap</li>
            </ul>
          </div>
        </div>

        {/* Renters */}
        <div className="flex gap-3 rounded-md p-3 -mx-1" style={{ background: 'rgba(200,134,26,0.08)', borderLeft: `3px solid ${C.ochre}` }}>
          <span className="text-xl shrink-0">🏠</span>
          <div>
            <p className="font-semibold" style={{ color: C.ochre }}>If you rent</p>
            <p className="mt-0.5" style={{ color: C.ink }}>
              Your landlord is responsible for maintaining plumbing that is safe. Ohio law requires
              landlords to disclose known lead hazards. If you believe your rental has lead pipes
              or lead paint, contact{' '}
              <a href="https://www.cincinnati-oh.gov/buildings/" target="_blank" rel="noopener noreferrer" className="underline" style={{ color: C.river }}>
                Cincinnati Buildings &amp; Inspections
              </a>{' '}
              at 513-591-6000, or{' '}
              <a href="https://www.cincylegalaid.org/" target="_blank" rel="noopener noreferrer" className="underline" style={{ color: C.river }}>
                Legal Aid Society of Greater Cincinnati
              </a>{' '}
              for tenant rights assistance.
            </p>
          </div>
        </div>
      </div>
    </DataCard>
  );
}

/** City-wide neighborhood comparison bar chart */
function CityWideComparisonCard() {
  const [allStats, setAllStats] = useState<NeighborhoodLeadStats[]>([]);
  const [loading, setLoading] = useState(true);
  const [notBuilt, setNotBuilt] = useState(false);

  useEffect(() => {
    fetchNeighborhoodLeadStats()
      .then((map) => {
        if (map.size === 0) {
          setNotBuilt(true);
          return;
        }
        const sorted = Array.from(map.values())
          .filter((s) => s.total > 0)
          .sort((a, b) => (b.lead + b.unknown) / b.total - (a.lead + a.unknown) / a.total);
        setAllStats(sorted);
      })
      .catch(() => setNotBuilt(true))
      .finally(() => setLoading(false));
  }, []);

  const chartData = useMemo(
    () =>
      allStats.map((s) => ({
        name: s.name.length > 14 ? s.name.slice(0, 13) + '…' : s.name,
        fullName: s.name,
        pct: Math.round(((s.lead + s.unknown) / s.total) * 100),
      })),
    [allStats]
  );

  if (notBuilt) return null; // Don't show the section if data isn't built yet

  return (
    <DataCard
      title="City-Wide Comparison — % Lead or Unknown Lines by Neighborhood"
      loading={loading}
      error={null}
      attribution={{ datasetName: 'GCWW Lead Service Line Inventory', lastUpdated: null }}
    >
      {chartData.length === 0 && !loading ? (
        <p className="text-[13px]" style={{ color: C.muted }}>No city-wide comparison data available.</p>
      ) : (
        <div>
          <p className="text-[11px] mb-3" style={{ color: C.muted }}>
            Neighborhoods sorted by percentage of service lines that are confirmed lead or
            unknown material. Higher = more residents potentially at risk.
          </p>
          <p className="text-[11px] rounded px-2 py-1 mb-3" style={{ color: C.ochre, background: 'rgba(200,134,26,0.08)', border: `1px solid ${C.ochre}` }}>
            Note: GCWW serves a regional area. This chart includes some suburban municipalities
            (e.g., Anderson Township, Blue Ash, Cheviot) in addition to Cincinnati neighborhoods.
          </p>
          <div style={{ height: Math.max(300, chartData.length * 22) }}>
            <ResponsiveContainer width="100%" height="100%">
              <BarChart
                layout="vertical"
                data={chartData}
                margin={{ top: 0, right: 40, bottom: 0, left: 120 }}
              >
                <XAxis
                  type="number"
                  domain={[0, 100]}
                  tickFormatter={(v) => `${v}%`}
                  tick={{ fontSize: 11, fill: C.muted }}
                />
                <YAxis
                  type="category"
                  dataKey="name"
                  tick={{ fontSize: 10, fill: C.muted }}
                  width={115}
                />
                <Tooltip
                  formatter={(v: number, _name, props) => [
                    `${v}%`,
                    `Lead or unknown — ${props.payload?.fullName ?? ''}`,
                  ]}
                  contentStyle={{ fontSize: '12px', borderColor: C.rule, borderRadius: 6 }}
                />
                <Bar dataKey="pct" radius={[0, 2, 2, 0]}>
                  {chartData.map((entry, i) => (
                    <Cell
                      key={i}
                      fill={
                        entry.pct > 50 ? C.brick
                        : entry.pct > 25 ? C.ochre
                        : entry.pct > 10 ? '#8a6e3e'
                        : C.hill
                      }
                    />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      )}
    </DataCard>
  );
}

// ── Material code helpers ─────────────────────────────────────────────────────

function materialLabel(code: string | undefined): string {
  if (!code) return 'Unknown';
  const c = code.toUpperCase();
  if (c === 'PB') return 'Lead';
  if (c === 'CU') return 'Copper';
  if (c === 'GS' || c === 'GI') return 'Galvanized';
  if (c === 'LDNR') return 'Lead (do not replace)';
  if (c === 'UN' || c === 'UNK') return 'Unknown';
  return code; // pass through any other codes as-is
}

function materialRisk(code: string | undefined): { label: string; style: React.CSSProperties; badgeStyle: React.CSSProperties } {
  const base: React.CSSProperties = { padding: '2px 8px', borderRadius: 4, fontSize: 11, fontWeight: 500 }
  if (!code) return { label: 'Unknown', style: { background: C.limestone }, badgeStyle: { ...base, color: C.muted, background: C.limestone, border: `1px solid ${C.rule}` } };
  const c = code.toUpperCase();
  if (c === 'PB' || c === 'LDNR') return { label: 'Lead — action recommended', style: { background: C.brickLight }, badgeStyle: { ...base, color: C.brick, background: C.brickLight, border: `1px solid ${C.brick}` } };
  if (c === 'GS' || c === 'GI') return { label: 'Galvanized — may carry lead deposits', style: { background: 'rgba(200,134,26,0.1)' }, badgeStyle: { ...base, color: C.ochre, background: 'rgba(200,134,26,0.1)', border: `1px solid ${C.ochre}` } };
  if (c === 'UN' || c === 'UNK') return { label: 'Unknown material', style: { background: C.limestone }, badgeStyle: { ...base, color: C.ochre, background: C.limestone, border: `1px solid ${C.ochre}` } };
  if (c === 'CU') return { label: 'Copper — lower risk', style: { background: C.hillLight }, badgeStyle: { ...base, color: C.hill, background: C.hillLight, border: `1px solid ${C.hill}` } };
  return { label: code, style: { background: C.limestone }, badgeStyle: { ...base, color: C.muted, background: C.limestone, border: `1px solid ${C.rule}` } };
}

function statusLabel(status: string | undefined): string {
  if (!status) return 'Unknown';
  const s = status.toUpperCase();
  if (s === 'COMPLETE') return 'Replacement complete';
  if (s === 'IN PROGRESS' || s === 'INPROGRESS') return 'Replacement in progress';
  if (s === 'PENDING') return 'Pending replacement';
  if (s === 'SCHEDULED') return 'Scheduled';
  return status;
}

/**
 * Address lookup card — lets residents check if their specific address is
 * enrolled in the GCWW lead service line replacement program.
 *
 * Queries b4xq-u3su with a LIKE match on the address field. The dataset covers
 * ~6,400 program lines, not the full city-wide inventory of 33,449, so a
 * "not found" result doesn't confirm a copper line — it means the address hasn't
 * been formally evaluated and enrolled in the program yet.
 */
function AddressSearchCard() {
  const [query, setQuery] = useState('');
  const [results, setResults] = useState<LeadReplacementRecord[] | null>(null);
  const [loading, setLoading] = useState(false);
  const [searched, setSearched] = useState(false);

  async function handleSearch(e: React.FormEvent) {
    e.preventDefault();
    if (query.trim().length < 3) return;
    setLoading(true);
    setSearched(false);
    try {
      const data = await searchLeadByAddress(query);
      setResults(data);
    } catch {
      setResults([]);
    } finally {
      setLoading(false);
      setSearched(true);
    }
  }

  return (
    <DataCard
      title="Look Up Your Address"
      loading={false}
      error={null}
    >
      <p className="text-[13px] mb-4" style={{ color: C.muted }}>
        Check if your address is enrolled in GCWW's lead service line replacement program
        and see its current status.
      </p>

      <form onSubmit={handleSearch} className="flex gap-2 mb-4">
        <input
          type="text"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Enter street address, e.g. 1600 Vine St"
          className="flex-1 px-3 py-2 text-[13px] rounded-md focus:outline-none"
          style={{ border: `1px solid ${C.rule}`, background: C.paper, color: C.ink, fontFamily: '"Public Sans", sans-serif' }}
          minLength={3}
          aria-label="Street address"
        />
        <button
          type="submit"
          disabled={loading || query.trim().length < 3}
          className="px-4 py-2 text-[13px] font-medium rounded-md transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          style={{ background: C.river, color: '#fff' }}
        >
          {loading ? 'Searching…' : 'Search'}
        </button>
      </form>

      {/* Results */}
      {searched && results !== null && (
        results.length === 0 ? (
          <div className="rounded-md p-4 text-[13px]" style={{ background: C.limestone, border: `1px solid ${C.rule}`, color: C.ink }}>
            <p className="font-semibold mb-1">No results found for "{query}"</p>
            <p style={{ color: C.muted }}>
              This address may not be enrolled in GCWW's formal replacement program yet —
              the dataset covers ~6,400 evaluated lines, not all 33,449 citywide. It does{' '}
              <strong>not</strong> confirm a copper or lead-free line.
            </p>
            <p className="mt-2" style={{ color: C.muted }}>
              For address-level detail, use the{' '}
              <a
                href="https://gcww.maps.arcgis.com/apps/webappviewer/index.html?id=0a170c268c694e46a8a4e394630df0bd"
                target="_blank"
                rel="noopener noreferrer"
                className="underline"
                style={{ color: C.river }}
              >
                GCWW interactive service line map
              </a>.
            </p>
          </div>
        ) : (
          <div className="space-y-3">
            <p className="text-xs text-gray-500">
              {results.length} result{results.length !== 1 ? 's' : ''} from the GCWW replacement program
            </p>
            {results.map((r, i) => {
              const risk = materialRisk(r.privatematerialtype);
              return (
                <div key={i} className="rounded-md p-4" style={{ ...risk.style, border: `1px solid ${C.rule}` }}>
                  <div className="flex items-start justify-between gap-2 flex-wrap">
                    <div>
                      <p className="font-semibold text-[13px]" style={{ color: C.ink }}>{r.address ?? 'Unknown address'}</p>
                      {r.adminarea && (
                        <p className="text-[11px] mt-0.5" style={{ color: C.muted }}>{r.adminarea}</p>
                      )}
                    </div>
                    <span style={risk.badgeStyle}>{risk.label}</span>
                  </div>
                  <div className="mt-3 grid grid-cols-2 gap-x-4 gap-y-1 text-[12px]">
                    <div>
                      <span style={{ color: C.muted }}>Private-side material: </span>
                      <span className="font-medium" style={{ color: C.ink }}>{materialLabel(r.privatematerialtype)}</span>
                    </div>
                    <div>
                      <span style={{ color: C.muted }}>Public-side material: </span>
                      <span className="font-medium" style={{ color: C.ink }}>{materialLabel(r.publicmaterialtype)}</span>
                    </div>
                    <div>
                      <span style={{ color: C.muted }}>Program status: </span>
                      <span className="font-medium" style={{ color: C.ink }}>{statusLabel(r.status)}</span>
                    </div>
                    {r.publicreplacedate && (
                      <div>
                        <span style={{ color: C.muted }}>Public-side replaced: </span>
                        <span className="font-medium" style={{ color: C.ink }}>{r.publicreplacedate.slice(0, 10)}</span>
                      </div>
                    )}
                  </div>
                </div>
              );
            })}
            <p className="text-[11px] mt-2" style={{ color: C.muted }}>
              Note: "Private-side" is the pipe from the curb to your home (your responsibility).
              "Public-side" is the pipe from the main to the curb (GCWW's responsibility).
              Both must be lead-free for safe water.
            </p>
          </div>
        )
      )}

      {/* Always-on context note */}
      <div className="mt-4 rounded-md px-3 py-2 text-[12px]" style={{ background: C.riverLight, borderLeft: `3px solid ${C.river}`, color: C.ink }}>
        <strong>Coverage note:</strong> This dataset tracks ~6,400 service lines formally
        enrolled in GCWW's replacement program — not the full city-wide inventory of 33,449
        lead or unknown lines. If your address doesn't appear, contact GCWW at{' '}
        <a href="tel:5135914600" className="underline" style={{ color: C.river }}>(513) 591-4600</a> to request an
        assessment.
      </div>
    </DataCard>
  );
}

/** Data transparency / gaps card */
function DataGapsCard() {
  return (
    <DataCard
      title="Data Gaps & What We're Missing"
      loading={false}
      error={null}
    >
      <div className="space-y-3 text-[13px]" style={{ color: C.ink }}>
        <div className="flex gap-3 items-start">
          <span className="text-lg shrink-0">🩸</span>
          <div>
            <p className="font-semibold">Blood lead case rates by neighborhood are not yet machine-readable</p>
            <p className="mt-0.5" style={{ color: C.muted }}>
              The Cincinnati Health Department's{' '}
              <a
                href="https://www.cincinnati-oh.gov/sites/health/assets/2024-LEAD-ANNUAL-REPORT.pdf"
                target="_blank"
                rel="noopener noreferrer"
                className="underline"
                style={{ color: C.river }}
              >
                2024 Lead Annual Report
              </a>{' '}
              contains census tract maps of testing rates and elevated prevalence (2015–2024 averages),
              but the underlying data isn't published in a downloadable format. We're pursuing a
              public records request for the census tract table that powers those maps — if successful,
              this tab will show which neighborhoods have the highest pediatric lead burden alongside
              the service line data. Small-cell suppression may limit tract-level disclosure for
              low-count areas.
            </p>
          </div>
        </div>
        <div className="flex gap-3 items-start">
          <span className="text-lg shrink-0">🏗️</span>
          <div>
            <p className="font-semibold">Private-side inventory is based on GCWW records</p>
            <p className="mt-0.5" style={{ color: C.muted }}>
              GCWW's inventory comes from water main and service line records, maintenance history,
              and repair/replacement work — not physical inspections of every property. Unknown
              lines are those without confirmed documentation. The true number of lead lines may
              be higher or lower.
            </p>
          </div>
        </div>
        <div className="flex gap-3 items-start">
          <span className="text-lg shrink-0">🏚️</span>
          <div>
            <p className="font-semibold">Interior plumbing and lead paint are outside this data</p>
            <p className="mt-0.5" style={{ color: C.muted }}>
              Service line status tells you about the pipe from the street to your home. Older
              interior plumbing, faucets, and lead paint in pre-1978 housing are separate and
              significant sources of lead exposure — especially for children.
            </p>
          </div>
        </div>
        <div className="mt-4 rounded-md p-3" style={{ background: C.limestone, border: `1px solid ${C.rule}` }}>
          <p className="font-semibold" style={{ color: C.river }}>Sources</p>
          <ul className="mt-1 space-y-1 text-[11px]" style={{ color: C.muted }}>
            <li>
              <a href="https://la.mygcww.org/neighborhood-stats/" target="_blank" rel="noopener noreferrer" className="underline" style={{ color: C.river }}>
                GCWW Neighborhood Stats
              </a>{' '}
              — neighborhood-level inventory breakdown
            </li>
            <li>
              <a href="https://data.cincinnati-oh.gov/dataset/GCWW-Private-Side-One-off-Lead-Service-Line-Replac/b4xq-u3su" target="_blank" rel="noopener noreferrer" className="underline" style={{ color: C.river }}>
                Cincinnati Open Data: GCWW Lead Replacements
              </a>{' '}
              — completed private-side replacements
            </li>
            <li>
              <a href="https://gcww.maps.arcgis.com/apps/webappviewer/index.html?id=0a170c268c694e46a8a4e394630df0bd" target="_blank" rel="noopener noreferrer" className="underline" style={{ color: C.river }}>
                GCWW Service Line Map
              </a>{' '}
              — interactive address-level map
            </li>
          </ul>
        </div>
      </div>
    </DataCard>
  );
}

// ── Main component ─────────────────────────────────────────────────────────────

export default function LeadSafety() {
  const [neighborhood, setNeighborhood] = useState('Over-the-Rhine');

  return (
    <div className="px-8 py-2 space-y-5">
      {/* City-wide urgency banner */}
      <UrgencyBanner />

      {/* Neighborhood selector */}
      <div className="page-paper rounded-md p-4 flex flex-wrap items-center gap-4">
        <span className="smallcaps" style={{ color: C.muted }}>Neighborhood</span>
        <select
          id="lead-neighborhood"
          value={neighborhood}
          onChange={(e) => setNeighborhood(e.target.value)}
          className="appearance-none pl-3 pr-8 py-1.5 rounded-md font-medium text-[14px] cursor-pointer"
          style={{
            background: C.paper,
            color: C.ink,
            border: `1px solid ${C.rule}`,
            fontFamily: 'Newsreader, serif',
          }}
        >
          {NEIGHBORHOODS.map((n) => (
            <option key={n} value={n}>{n}</option>
          ))}
        </select>
      </div>

      {/* Address lookup — resident-facing, above neighborhood cards */}
      <AddressSearchCard />

      {/* Two-column grid for the per-neighborhood cards */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <InventoryCard neighborhood={neighborhood} />
        <ReplacementActivityCard neighborhood={neighborhood} />
      </div>

      {/* What to do */}
      <ActionCard />

      {/* City-wide comparison */}
      <CityWideComparisonCard />

      {/* Data gaps */}
      <DataGapsCard />
    </div>
  );
}
