/**
 * Lead Safety Tab — Cincinnati Civic Data Platform
 *
 * Shows GCWW lead service line inventory by neighborhood, replacement program
 * activity, and actionable guidance for residents in affected areas.
 *
 * Data sources:
 *   - /data/lead_service_lines.json   — pre-built neighborhood inventory
 *     (generated by scripts/build_lead.py from GCWW open data)
 *   - Cincinnati Open Data `ntfu-vnkd` — live GCWW replacement records
 *
 * Why this matters:
 *   - 33,449 lead or unknown service lines remain in Cincinnati
 *   - ~220 children are diagnosed with elevated blood lead levels each year
 *   - Only 36.8% of children under 6 are tested
 *   - No publicly accessible civic map existed before this tab
 *
 * The tab gracefully handles the pre-built file being absent ({}) by showing
 * a build notice instead of an error, and still shows live replacement activity.
 */

import { useState, useEffect, useMemo } from 'react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell } from 'recharts';
import {
  fetchNeighborhoodLeadStats,
  fetchLeadReplacements,
  stripNeighborhoodName,
} from '../../utils/api';
import type { LeadReplacementRecord } from '../../utils/api';
import type { NeighborhoodLeadStats } from '../../types';
import { DataCard } from '../../components/ui';

// ── Neighborhood list ─────────────────────────────────────────────────────────

const NEIGHBORHOODS = [
  'Avondale', 'Bond Hill', 'California', 'Camp Washington', 'Carthage',
  'CBD / Riverfront', 'Clifton', 'Clifton Heights', 'College Hill',
  'Columbia-Tusculum', 'Corryville', 'East End', 'East Price Hill',
  'East Walnut Hills', 'East Westwood', 'English Woods', 'Evanston',
  'Fairview', 'Fay Apartments', 'Hartwell', 'Hyde Park', 'Kennedy Heights',
  'Linwood', 'Lower Price Hill', 'Madisonville', 'Millvale', 'Mount Adams',
  'Mount Airy', 'Mount Auburn', 'Mt. Lookout', 'Mt. Washington',
  'North Avondale', 'North Fairmount', 'Northside', 'Oakley', "O'Bryonville",
  'Over-the-Rhine', 'Paddock Hills', 'Pendleton', 'Pleasant Ridge', 'Queensgate',
  'Riverside', 'Roselawn', 'Sayler Park', 'Sedamsville', 'South Cumminsville',
  'South Fairmount', 'Spring Grove Village', 'Walnut Hills', 'West End',
  'West Price Hill', 'Westwood', 'Winton Hills',
];

// ── Helpers ───────────────────────────────────────────────────────────────────

function pct(numerator: number, denominator: number): string {
  if (!denominator) return 'N/A';
  return `${Math.round((numerator / denominator) * 100)}%`;
}

function riskColor(leadOrUnknown: number, total: number): string {
  if (!total) return 'text-gray-500 bg-gray-50';
  const rate = leadOrUnknown / total;
  if (rate > 0.5) return 'text-red-700 bg-red-50';
  if (rate > 0.25) return 'text-orange-700 bg-orange-50';
  if (rate > 0.1) return 'text-yellow-700 bg-yellow-50';
  return 'text-green-700 bg-green-50';
}

function riskLabel(leadOrUnknown: number, total: number): string {
  if (!total) return 'No Data';
  const rate = leadOrUnknown / total;
  if (rate > 0.5) return 'High Risk';
  if (rate > 0.25) return 'Elevated Risk';
  if (rate > 0.1) return 'Moderate Risk';
  return 'Lower Risk';
}

// ── Sub-components ────────────────────────────────────────────────────────────

/** Stat row used in the inventory breakdown */
function StatRow({
  label,
  value,
  barWidth,
  barColor,
  note,
}: {
  label: string;
  value: number | string;
  barWidth?: number; // 0–100 for visual bar
  barColor?: string;
  note?: string;
}) {
  return (
    <div className="py-2 border-b border-gray-100 last:border-0">
      <div className="flex justify-between items-center">
        <div>
          <span className="text-sm text-gray-700">{label}</span>
          {note && <p className="text-xs text-gray-500 mt-0.5">{note}</p>}
        </div>
        <span className="text-sm font-semibold text-[#1A4A6B] ml-4 shrink-0">
          {typeof value === 'number' ? value.toLocaleString() : value}
        </span>
      </div>
      {barWidth !== undefined && (
        <div className="mt-1.5 h-1.5 bg-gray-100 rounded-full overflow-hidden">
          <div
            className={`h-full rounded-full transition-all duration-500 ${barColor ?? 'bg-blue-400'}`}
            style={{ width: `${Math.min(barWidth, 100)}%` }}
          />
        </div>
      )}
    </div>
  );
}

/** Urgency header with city-wide lead crisis stats */
function UrgencyBanner() {
  return (
    <div className="bg-red-900 text-white rounded-xl p-6 mb-6">
      <div className="flex items-start gap-3 mb-4">
        <span className="text-3xl" role="img" aria-label="warning">⚠️</span>
        <div>
          <h2 className="text-xl font-bold">Lead in Cincinnati's Water Lines</h2>
          <p className="text-red-200 text-sm mt-1">
            Lead-free water isn't guaranteed for every household in Cincinnati.
            Thousands of service lines — the pipes connecting the main to your home — are still
            lead or unidentified material.
          </p>
        </div>
      </div>
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        {[
          { value: '33,449', label: 'Lead or unknown lines remaining', sub: 'As of 2024' },
          { value: '~220', label: 'Children with elevated blood lead yearly', sub: 'City of Cincinnati' },
          { value: '36.8%', label: 'Children under 6 who are tested', sub: 'Far below national average' },
          { value: '$0', label: 'Cost to residents for city-side replacement', sub: 'Private-side may have costs' },
        ].map(({ value, label, sub }) => (
          <div key={label} className="bg-red-800 bg-opacity-60 rounded-lg p-3 text-center">
            <div className="text-2xl font-bold">{value}</div>
            <div className="text-xs text-red-200 mt-1">{label}</div>
            <div className="text-xs text-red-300 mt-0.5">{sub}</div>
          </div>
        ))}
      </div>
    </div>
  );
}

/** Inventory section — loaded from pre-built JSON */
function InventoryCard({ neighborhood }: { neighborhood: string }) {
  const [stats, setStats] = useState<NeighborhoodLeadStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [notBuilt, setNotBuilt] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setLoading(true);
    setStats(null);
    setError(null);
    setNotBuilt(false);

    fetchNeighborhoodLeadStats()
      .then((map) => {
        if (map.size === 0) {
          setNotBuilt(true);
          return;
        }
        const key = stripNeighborhoodName(neighborhood);
        const found = map.get(key) ?? null;
        setStats(found);
      })
      .catch((e) => setError(String(e)))
      .finally(() => setLoading(false));
  }, [neighborhood]);

  if (notBuilt) {
    return (
      <DataCard
        title="Service Line Inventory"
        loading={false}
        error={null}
        attribution={{ datasetName: 'GCWW Lead Service Line Inventory', lastUpdated: null }}
      >
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 text-sm text-amber-900 space-y-2">
          <p className="font-semibold">⚙️ Pre-computed data not yet generated</p>
          <p>
            The full service line inventory requires a one-time build step. Run this command
            in the project directory to generate the data:
          </p>
          <pre className="bg-amber-100 rounded p-2 text-xs font-mono overflow-x-auto">
            python3 scripts/build_lead.py
          </pre>
          <p>
            Once generated, <code className="text-xs bg-amber-100 px-1 rounded">public/data/lead_service_lines.json</code> will
            populate this section with lead/unknown/copper counts for all 52 neighborhoods.
          </p>
          <p>
            In the meantime, the <strong>Replacement Activity</strong> card below shows live data
            from Cincinnati's open data portal.
          </p>
        </div>
      </DataCard>
    );
  }

  const leadOrUnknown = stats ? stats.lead + stats.unknown : 0;

  return (
    <DataCard
      title="Service Line Inventory"
      loading={loading}
      error={error}
      attribution={{ datasetName: 'GCWW Lead Service Line Inventory', lastUpdated: stats?.asOf ?? null }}
    >
      {stats === null && !loading ? (
        <p className="text-sm text-gray-500">No inventory data found for {neighborhood}.</p>
      ) : stats ? (
        <div className="space-y-2">
          {/* Risk badge */}
          <div className={`inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-sm font-semibold mb-3 ${riskColor(leadOrUnknown, stats.total)}`}>
            <span>{riskLabel(leadOrUnknown, stats.total)}</span>
            <span className="font-normal opacity-75">·</span>
            <span>{pct(leadOrUnknown, stats.total)} of lines are lead or unknown</span>
          </div>

          {/* Breakdown */}
          <StatRow
            label="Lead service lines"
            value={stats.lead}
            barWidth={stats.total ? (stats.lead / stats.total) * 100 : 0}
            barColor="bg-red-500"
            note="Confirmed lead material — replacement is a priority"
          />
          <StatRow
            label="Unknown material"
            value={stats.unknown}
            barWidth={stats.total ? (stats.unknown / stats.total) * 100 : 0}
            barColor="bg-orange-400"
            note="Material unconfirmed — treated as potentially lead"
          />
          <StatRow
            label="Galvanized steel"
            value={stats.galvanized}
            barWidth={stats.total ? (stats.galvanized / stats.total) * 100 : 0}
            barColor="bg-yellow-400"
            note="Corrosion concern; may have been connected to a lead line"
          />
          <StatRow
            label="Copper or safe material"
            value={stats.copper}
            barWidth={stats.total ? (stats.copper / stats.total) * 100 : 0}
            barColor="bg-green-500"
            note="Confirmed non-lead material"
          />
          <StatRow
            label="Already replaced"
            value={stats.replaced}
            barWidth={stats.total ? (stats.replaced / stats.total) * 100 : 0}
            barColor="bg-blue-500"
            note="Private-side replacement completed through GCWW program"
          />
          <div className="pt-2 border-t border-gray-100 flex justify-between items-center">
            <span className="text-sm text-gray-500">Total service lines</span>
            <span className="text-sm font-bold text-[#1A4A6B]">{stats.total.toLocaleString()}</span>
          </div>
        </div>
      ) : null}
    </DataCard>
  );
}

/** Replacement Activity card — live SODA data from ntfu-vnkd */
function ReplacementActivityCard({ neighborhood }: { neighborhood: string }) {
  const [records, setRecords] = useState<LeadReplacementRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setLoading(true);
    setError(null);
    fetchLeadReplacements(neighborhood)
      .then(setRecords)
      .catch((e) => setError(String(e)))
      .finally(() => setLoading(false));
  }, [neighborhood]);

  // Group by year for chart
  const yearData = useMemo(() => {
    const counts: Record<string, number> = {};
    for (const r of records) {
      // Try to parse year from date_completed — field name unconfirmed until live test
      const raw = r.date_completed ?? '';
      const year = raw.slice(0, 4);
      if (/^\d{4}$/.test(year)) {
        counts[year] = (counts[year] ?? 0) + 1;
      }
    }
    return Object.entries(counts)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([year, count]) => ({ year, count }));
  }, [records]);

  const total = records.length;

  return (
    <DataCard
      title="Replacement Program Activity"
      loading={loading}
      error={error}
      attribution={{
        datasetName: 'GCWW Private-Side Lead Service Line Replacements',
        lastUpdated: null,
        uid: 'ntfu-vnkd',
      }}
    >
      {total === 0 && !loading ? (
        <div className="text-sm text-gray-500 space-y-1">
          <p>No replacement records found for {neighborhood}.</p>
          <p className="text-xs text-gray-400">
            This may mean the dataset has no records matching this neighborhood name, or that
            the live query returned an unexpected field format. Field names in this dataset
            have not yet been confirmed through live testing.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          <div className="bg-blue-50 rounded-lg px-4 py-3 flex items-center justify-between">
            <div>
              <div className="text-2xl font-bold text-[#1A4A6B]">{total.toLocaleString()}</div>
              <div className="text-sm text-gray-600">Private-side replacements recorded</div>
            </div>
            <div className="text-right text-xs text-gray-500">
              <p>This dataset records private-side</p>
              <p>replacements completed through</p>
              <p>GCWW's program</p>
            </div>
          </div>

          {yearData.length > 0 && (
            <div>
              <p className="text-xs text-gray-500 mb-2">Replacements by year</p>
              <ResponsiveContainer width="100%" height={140}>
                <BarChart data={yearData} margin={{ top: 4, right: 4, bottom: 4, left: 0 }}>
                  <XAxis dataKey="year" tick={{ fontSize: 11 }} />
                  <YAxis tick={{ fontSize: 11 }} width={30} />
                  <Tooltip
                    formatter={(v: number) => [v, 'Replacements']}
                    contentStyle={{ fontSize: '12px' }}
                  />
                  <Bar dataKey="count" fill="#1A4A6B" radius={[2, 2, 0, 0]}>
                    {yearData.map((_, i) => (
                      <Cell
                        key={i}
                        fill={i === yearData.length - 1 ? '#E95B2E' : '#1A4A6B'}
                      />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
              <p className="text-xs text-gray-400 mt-1">Most recent year highlighted in orange.</p>
            </div>
          )}

          <p className="text-xs text-gray-500">
            Note: "Private-side" means the pipe from the curb to your home. The city-side
            (main to curb) replacement is handled separately and is not in this dataset.
          </p>
        </div>
      )}
    </DataCard>
  );
}

/** What to do if you're in a lead-risk neighborhood */
function ActionCard() {
  return (
    <DataCard
      title="What You Can Do"
      loading={false}
      error={null}
    >
      <div className="space-y-4 text-sm text-gray-700">
        {/* Check your address */}
        <div className="flex gap-3">
          <span className="text-xl shrink-0">🔍</span>
          <div>
            <p className="font-semibold text-gray-900">Look up your specific address</p>
            <p className="mt-0.5">
              GCWW's Lead Line Lookup shows the status of the public-side line for your address.{' '}
              <a
                href="https://utility.cincinnati-oh.gov/WaterCheck/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-[#1A4A6B] underline"
              >
                Search your address at utility.cincinnati-oh.gov
              </a>
              . For the private-side (inside your property), you or your plumber would need to
              identify the pipe material.
            </p>
          </div>
        </div>

        {/* Test your water */}
        <div className="flex gap-3">
          <span className="text-xl shrink-0">🧪</span>
          <div>
            <p className="font-semibold text-gray-900">Get your water tested</p>
            <p className="mt-0.5">
              Even if your service line is listed as copper, older interior plumbing and
              solder joints can leach lead. GCWW offers{' '}
              <a
                href="https://la.mygcww.org/lead/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-[#1A4A6B] underline"
              >
                free lead water testing kits
              </a>{' '}
              for Cincinnati customers.
            </p>
          </div>
        </div>

        {/* Apply for replacement */}
        <div className="flex gap-3">
          <span className="text-xl shrink-0">🔧</span>
          <div>
            <p className="font-semibold text-gray-900">Apply for free replacement</p>
            <p className="mt-0.5">
              Cincinnati's Lead Service Line Replacement Program (LSLRP) replaces both the
              public-side and private-side at <strong>no cost to the homeowner</strong> when
              your home is selected. GCWW prioritizes homes with children under 6, pregnant
              residents, and older housing stock. Contact{' '}
              <a
                href="https://la.mygcww.org/lead/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-[#1A4A6B] underline"
              >
                GCWW's lead program
              </a>{' '}
              or call <strong>513-591-7700</strong> to ask about your eligibility.
            </p>
          </div>
        </div>

        {/* Protect your family in the meantime */}
        <div className="flex gap-3">
          <span className="text-xl shrink-0">🚰</span>
          <div>
            <p className="font-semibold text-gray-900">Reduce exposure while you wait</p>
            <ul className="mt-0.5 list-disc list-inside space-y-0.5 text-gray-600">
              <li>Run cold water for 1–2 minutes before drinking or cooking if pipes have sat unused</li>
              <li>Use cold (never hot) water for drinking and cooking — hot water leaches more lead</li>
              <li>Use an NSF-certified lead filter (pitcher or faucet-mount)</li>
              <li>Never give young children water from the hot tap</li>
            </ul>
          </div>
        </div>

        {/* Renters */}
        <div className="flex gap-3 bg-amber-50 rounded-lg p-3 -mx-1">
          <span className="text-xl shrink-0">🏠</span>
          <div>
            <p className="font-semibold text-amber-900">If you rent</p>
            <p className="mt-0.5 text-amber-800">
              Your landlord is responsible for maintaining plumbing that is safe. Ohio law requires
              landlords to disclose known lead hazards. If you believe your rental has lead pipes
              or lead paint, contact{' '}
              <a
                href="https://www.cincinnati-oh.gov/buildings/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-[#1A4A6B] underline"
              >
                Cincinnati Buildings & Inspections
              </a>{' '}
              at 513-591-6000, or{' '}
              <a
                href="https://www.cincylegalaid.org/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-[#1A4A6B] underline"
              >
                Legal Aid Society of Greater Cincinnati
              </a>{' '}
              for tenant rights assistance.
            </p>
          </div>
        </div>
      </div>
    </DataCard>
  );
}

/** City-wide neighborhood comparison bar chart */
function CityWideComparisonCard() {
  const [allStats, setAllStats] = useState<NeighborhoodLeadStats[]>([]);
  const [loading, setLoading] = useState(true);
  const [notBuilt, setNotBuilt] = useState(false);

  useEffect(() => {
    fetchNeighborhoodLeadStats()
      .then((map) => {
        if (map.size === 0) {
          setNotBuilt(true);
          return;
        }
        const sorted = Array.from(map.values())
          .filter((s) => s.total > 0)
          .sort((a, b) => (b.lead + b.unknown) / b.total - (a.lead + a.unknown) / a.total);
        setAllStats(sorted);
      })
      .catch(() => setNotBuilt(true))
      .finally(() => setLoading(false));
  }, []);

  const chartData = useMemo(
    () =>
      allStats.map((s) => ({
        name: s.name.length > 14 ? s.name.slice(0, 13) + '…' : s.name,
        fullName: s.name,
        pct: Math.round(((s.lead + s.unknown) / s.total) * 100),
      })),
    [allStats]
  );

  if (notBuilt) return null; // Don't show the section if data isn't built yet

  return (
    <DataCard
      title="City-Wide Comparison — % Lead or Unknown Lines by Neighborhood"
      loading={loading}
      error={null}
      attribution={{ datasetName: 'GCWW Lead Service Line Inventory', lastUpdated: null }}
    >
      {chartData.length === 0 && !loading ? (
        <p className="text-sm text-gray-500">No city-wide comparison data available.</p>
      ) : (
        <div>
          <p className="text-xs text-gray-500 mb-3">
            Neighborhoods sorted by percentage of service lines that are confirmed lead or
            unknown material. Higher = more residents potentially at risk.
          </p>
          <div style={{ height: Math.max(300, chartData.length * 22) }}>
            <ResponsiveContainer width="100%" height="100%">
              <BarChart
                layout="vertical"
                data={chartData}
                margin={{ top: 0, right: 40, bottom: 0, left: 120 }}
              >
                <XAxis
                  type="number"
                  domain={[0, 100]}
                  tickFormatter={(v) => `${v}%`}
                  tick={{ fontSize: 11 }}
                />
                <YAxis
                  type="category"
                  dataKey="name"
                  tick={{ fontSize: 10 }}
                  width={115}
                />
                <Tooltip
                  formatter={(v: number, _name, props) => [
                    `${v}%`,
                    `Lead or unknown — ${props.payload?.fullName ?? ''}`,
                  ]}
                  contentStyle={{ fontSize: '12px' }}
                />
                <Bar dataKey="pct" radius={[0, 2, 2, 0]}>
                  {chartData.map((entry, i) => (
                    <Cell
                      key={i}
                      fill={
                        entry.pct > 50 ? '#B91C1C'
                        : entry.pct > 25 ? '#EA580C'
                        : entry.pct > 10 ? '#CA8A04'
                        : '#16A34A'
                      }
                    />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      )}
    </DataCard>
  );
}

/** Data transparency / gaps card */
function DataGapsCard() {
  return (
    <DataCard
      title="Data Gaps & What We're Missing"
      loading={false}
      error={null}
    >
      <div className="space-y-3 text-sm text-gray-700">
        <div className="flex gap-3 items-start">
          <span className="text-lg shrink-0">🩸</span>
          <div>
            <p className="font-semibold">Blood lead case data is not available by neighborhood</p>
            <p className="text-gray-600 mt-0.5">
              Cincinnati Health Dept. tracks blood lead cases but does not publish neighborhood-level
              counts publicly — likely due to small-cell suppression to protect privacy. This makes
              it impossible to show which neighborhoods have the highest pediatric lead burden. We've
              flagged this as a data partnership opportunity with Cincinnati Health.
            </p>
          </div>
        </div>
        <div className="flex gap-3 items-start">
          <span className="text-lg shrink-0">🏗️</span>
          <div>
            <p className="font-semibold">Private-side inventory is based on GCWW records</p>
            <p className="text-gray-600 mt-0.5">
              GCWW's inventory comes from water main and service line records, maintenance history,
              and repair/replacement work — not physical inspections of every property. Unknown
              lines are those without confirmed documentation. The true number of lead lines may
              be higher or lower.
            </p>
          </div>
        </div>
        <div className="flex gap-3 items-start">
          <span className="text-lg shrink-0">🏚️</span>
          <div>
            <p className="font-semibold">Interior plumbing and lead paint are outside this data</p>
            <p className="text-gray-600 mt-0.5">
              Service line status tells you about the pipe from the street to your home. Older
              interior plumbing, faucets, and lead paint in pre-1978 housing are separate and
              significant sources of lead exposure — especially for children.
            </p>
          </div>
        </div>
        <div className="mt-4 bg-blue-50 rounded-lg p-3">
          <p className="font-semibold text-[#1A4A6B]">Sources</p>
          <ul className="mt-1 space-y-1 text-xs text-gray-600">
            <li>
              <a href="https://la.mygcww.org/neighborhood-stats/" target="_blank" rel="noopener noreferrer" className="underline text-[#1A4A6B]">
                GCWW Neighborhood Stats
              </a>{' '}
              — neighborhood-level inventory breakdown
            </li>
            <li>
              <a href="https://data.cincinnati-oh.gov/dataset/GCWW-Private-Side-One-off-Lead-Service-Line-Replac/b4xq-u3su" target="_blank" rel="noopener noreferrer" className="underline text-[#1A4A6B]">
                Cincinnati Open Data: GCWW Lead Replacements
              </a>{' '}
              — completed private-side replacements
            </li>
            <li>
              <a href="https://gcww.maps.arcgis.com/apps/webappviewer/index.html?id=0a170c268c694e46a8a4e394630df0bd" target="_blank" rel="noopener noreferrer" className="underline text-[#1A4A6B]">
                GCWW Service Line Map
              </a>{' '}
              — interactive address-level map
            </li>
          </ul>
        </div>
      </div>
    </DataCard>
  );
}

// ── Main component ─────────────────────────────────────────────────────────────

export default function LeadSafety() {
  const [neighborhood, setNeighborhood] = useState('Over-the-Rhine');

  return (
    <div className="space-y-6">
      {/* Page header */}
      <div>
        <h1 className="text-2xl font-bold text-[#1A4A6B]">Lead Safety</h1>
        <p className="text-gray-600 mt-1">
          Lead service line status, replacement program activity, and risk by neighborhood —
          sourced from Greater Cincinnati Water Works (GCWW) open data.
        </p>
      </div>

      {/* City-wide urgency banner */}
      <UrgencyBanner />

      {/* Neighborhood selector */}
      <div className="bg-white rounded-xl border border-gray-200 p-4">
        <label htmlFor="lead-neighborhood" className="block text-sm font-medium text-gray-700 mb-2">
          Select a neighborhood
        </label>
        <select
          id="lead-neighborhood"
          value={neighborhood}
          onChange={(e) => setNeighborhood(e.target.value)}
          className="w-full sm:w-80 border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#1A4A6B]"
        >
          {NEIGHBORHOODS.map((n) => (
            <option key={n} value={n}>{n}</option>
          ))}
        </select>
      </div>

      {/* Two-column grid for the per-neighborhood cards */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <InventoryCard neighborhood={neighborhood} />
        <ReplacementActivityCard neighborhood={neighborhood} />
      </div>

      {/* What to do */}
      <ActionCard />

      {/* City-wide comparison */}
      <CityWideComparisonCard />

      {/* Data gaps */}
      <DataGapsCard />
    </div>
  );
}
