/**
 * Accessibility Tab — Cincinnati Civic Data Platform
 *
 * Shows disability demographics, transit/paratransit coverage, and infrastructure
 * data for each Cincinnati neighborhood, with adjustable views by impairment type.
 *
 * Data sources:
 *   - Census ACS 5-Year 2022  → public/data/neighborhood_disability.json (pre-built)
 *   - SORTA GTFS               → public/data/sorta_stops.json (already loaded in Tab 1)
 *
 * The Census disability data file is generated by running:
 *   python3 scripts/build_disability.py
 * (Must be run locally — Census API is blocked from Cowork sandbox.)
 *
 * Planned additions (future sessions):
 *   - OpenStreetMap Overpass: curb cuts, wheelchair-accessible paths, accessible parking
 *   - CMS Care Compare: nursing homes, home health agencies, dialysis centers
 *   - SORTA GTFS wheelchair_boarding field (requires re-importing stops with accessibility flags)
 */

import { useState, useEffect, useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import {
  fetchNeighborhoodDisabilityStats,
  distanceMiles,
  stripNeighborhoodName,
  formatPercent,
} from '../../utils/api';
import type { NeighborhoodDisabilityStats } from '../../types';
import { DataCard } from '../../components/ui';

// ── Neighborhood list (matches Tab 2 — CPD SNA names) ────────────────────────

const NEIGHBORHOODS = [
  'Avondale', 'Bond Hill', 'California', 'Camp Washington', 'Carthage',
  'CBD / Riverfront', 'Clifton', 'Clifton Heights', 'College Hill',
  'Columbia-Tusculum', 'Corryville', 'East End', 'East Price Hill',
  'East Walnut Hills', 'East Westwood', 'English Woods', 'Evanston',
  'Fairview', 'Fay Apartments', 'Hartwell', 'Hyde Park', 'Kennedy Heights',
  'Linwood', 'Lower Price Hill', 'Madisonville', 'Millvale', 'Mount Adams',
  'Mount Airy', 'Mount Auburn', 'Mt. Lookout', 'Mt. Washington',
  'North Avondale', 'North Fairmount', 'Northside', 'Oakley', "O'Bryonville",
  'Over-the-Rhine', 'Paddock Hills', 'Pendleton', 'Pleasant Ridge', 'Queensgate',
  'Riverside', 'Roselawn', 'Sayler Park', 'Sedamsville', 'South Cumminsville',
  'South Fairmount', 'Spring Grove Village', 'Walnut Hills', 'West End',
  'West Price Hill', 'Westwood', 'Winton Hills',
];

// SORTA paratransit: ADA requires Access service within 3/4 mile of any fixed-route stop.
const ADA_PARATRANSIT_RADIUS_MILES = 0.75;

// Approximate neighborhood centroids used for paratransit coverage computation.
// These mirror the closest-centroid assignments in the Census build pipeline.
// Long-term: derive from the SNA GeoJSON centroids directly.
const NEIGHBORHOOD_CENTROIDS: Record<string, [number, number]> = {
  'Avondale':           [39.1312, -84.5009],
  'Bond Hill':          [39.1756, -84.4742],
  'California':         [39.0911, -84.4527],
  'Camp Washington':    [39.1217, -84.5369],
  'Carthage':           [39.1879, -84.4800],
  'CBD / Riverfront':   [39.1031, -84.5120],
  'Clifton':            [39.1440, -84.5178],
  'Clifton Heights':    [39.1298, -84.5235],
  'College Hill':       [39.1977, -84.5243],
  'Columbia-Tusculum':  [39.1037, -84.4561],
  'Corryville':         [39.1330, -84.5135],
  'East End':           [39.0950, -84.4368],
  'East Price Hill':    [39.1026, -84.5399],
  'East Walnut Hills':  [39.1252, -84.4873],
  'East Westwood':      [39.1433, -84.5688],
  'English Woods':      [39.1699, -84.5599],
  'Evanston':           [39.1453, -84.4898],
  'Fairview':           [39.1350, -84.5253],
  'Fay Apartments':     [39.1060, -84.5250],
  'Hartwell':           [39.2023, -84.5182],
  'Hyde Park':          [39.1434, -84.4558],
  'Kennedy Heights':    [39.1767, -84.4548],
  'Linwood':            [39.1079, -84.4708],
  'Lower Price Hill':   [39.1113, -84.5530],
  'Madisonville':       [39.1483, -84.4368],
  'Millvale':           [39.1244, -84.5548],
  'Mount Adams':        [39.1107, -84.4976],
  'Mount Airy':         [39.1803, -84.5488],
  'Mount Auburn':       [39.1179, -84.5054],
  'Mt. Lookout':        [39.1259, -84.4368],
  'Mt. Washington':     [39.0882, -84.4523],
  'North Avondale':     [39.1589, -84.4951],
  'North Fairmount':    [39.1443, -84.5546],
  'Northside':          [39.1607, -84.5358],
  'Oakley':             [39.1478, -84.4618],
  "O'Bryonville":       [39.1370, -84.4542],
  'Over-the-Rhine':     [39.1125, -84.5175],
  'Paddock Hills':      [39.1885, -84.4882],
  'Pendleton':          [39.1095, -84.5076],
  'Pleasant Ridge':     [39.1665, -84.4492],
  'Queensgate':         [39.1098, -84.5322],
  'Riverside':          [39.0917, -84.5142],
  'Roselawn':           [39.1725, -84.4714],
  'Sayler Park':        [39.0938, -84.6007],
  'Sedamsville':        [39.0980, -84.5775],
  'South Cumminsville': [39.1326, -84.5558],
  'South Fairmount':    [39.1199, -84.5493],
  'Spring Grove Village':[39.1612, -84.5536],
  'Walnut Hills':       [39.1300, -84.4885],
  'West End':           [39.1115, -84.5283],
  'West Price Hill':    [39.1152, -84.5666],
  'Westwood':           [39.1470, -84.5818],
  'Winton Hills':       [39.1927, -84.5026],
};

// ── Impairment view types ─────────────────────────────────────────────────────

type ImpairmentView = 'overview' | 'mobility' | 'vision' | 'hearing' | 'cognitive';

interface ViewConfig {
  id: ImpairmentView;
  label: string;
  icon: string;
  description: string;
}

const VIEWS: ViewConfig[] = [
  {
    id: 'overview',
    label: 'All Disabilities',
    icon: '♿',
    description: 'Population-level disability demographics, poverty crosswalk, and earnings gap.',
  },
  {
    id: 'mobility',
    label: 'Mobility & Physical',
    icon: '🦽',
    description: 'Ambulatory difficulty, ADA paratransit coverage, and accessible transit.',
  },
  {
    id: 'vision',
    label: 'Vision',
    icon: '👁',
    description: 'Vision difficulty rates and infrastructure relevant to the visually impaired.',
  },
  {
    id: 'hearing',
    label: 'Hearing',
    icon: '👂',
    description: 'Hearing difficulty rates and relevant community context.',
  },
  {
    id: 'cognitive',
    label: 'Cognitive & Independent Living',
    icon: '🧠',
    description: 'Cognitive difficulty and independent living difficulty rates.',
  },
];

// ── Helpers ──────────────────────────────────────────────────────────────────

function pct(numerator: number, denominator: number): number | null {
  if (!denominator) return null;
  return (numerator / denominator) * 100;
}

function statRow(label: string, value: string | null, note?: string) {
  return (
    <div className="flex justify-between items-start py-2 border-b border-gray-100 last:border-0">
      <div>
        <span className="text-sm text-gray-700">{label}</span>
        {note && <p className="text-xs text-gray-500 mt-0.5">{note}</p>}
      </div>
      <span className="text-sm font-semibold text-[#1A4A6B] ml-4 shrink-0">
        {value ?? 'N/A'}
      </span>
    </div>
  );
}

// Color scale for disability rates: green (low) → yellow → red (high)
function rateColor(rate: number): string {
  if (rate < 10) return 'text-green-700 bg-green-50';
  if (rate < 18) return 'text-yellow-700 bg-yellow-50';
  return 'text-red-700 bg-red-50';
}

// ── SORTA paratransit helpers ─────────────────────────────────────────────────

interface SORTAStop {
  stop_lat: number;
  stop_lon: number;
  stop_name: string;
  routes: string[];
}

async function loadSORTAStops(): Promise<SORTAStop[]> {
  const resp = await fetch('/data/sorta_stops.json');
  if (!resp.ok) throw new Error('SORTA stops unavailable');
  return resp.json();
}

// ── Sub-components ────────────────────────────────────────────────────────────

/** Big stat callout used in each view's key metrics section */
function StatCallout({
  value,
  label,
  sub,
  colorClass,
}: {
  value: string;
  label: string;
  sub?: string;
  colorClass?: string;
}) {
  return (
    <div className={`rounded-lg p-4 text-center ${colorClass ?? 'bg-blue-50'}`}>
      <div className={`text-3xl font-bold ${colorClass ? '' : 'text-[#1A4A6B]'}`}>{value}</div>
      <div className="text-sm font-medium mt-1">{label}</div>
      {sub && <div className="text-xs text-gray-500 mt-0.5">{sub}</div>}
    </div>
  );
}

/**
 * Paratransit coverage card — computes ADA Access coverage from SORTA stops.
 * The ADA requires complementary paratransit within 3/4 mile of any fixed route.
 */
function ParatransitCard({ neighborhood }: { neighborhood: string }) {
  const [stopsNearby, setStopsNearby] = useState<number | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const centroid = NEIGHBORHOOD_CENTROIDS[neighborhood];

  useEffect(() => {
    if (!centroid) {
      setError('No centroid data for this neighborhood.');
      setLoading(false);
      return;
    }
    setLoading(true);
    setError(null);
    loadSORTAStops()
      .then((stops) => {
        const [lat, lon] = centroid;
        const nearby = stops.filter(
          (s) => distanceMiles(lat, lon, s.stop_lat, s.stop_lon) <= ADA_PARATRANSIT_RADIUS_MILES
        ).length;
        setStopsNearby(nearby);
      })
      .catch((e) => setError(String(e)))
      .finally(() => setLoading(false));
  }, [neighborhood, centroid]);

  const covered = stopsNearby !== null && stopsNearby > 0;

  return (
    <DataCard
      title="ADA Paratransit Coverage (SORTA Access)"
      loading={loading}
      error={error}
      attribution={{ datasetName: 'SORTA GTFS Static Feed', lastUpdated: null, url: 'https://www.go-metro.com/about/developer-data/' }}
    >
      <div className="space-y-3">
        {/* Coverage status */}
        <div className={`flex items-center gap-3 p-3 rounded-lg ${covered ? 'bg-green-50' : 'bg-red-50'}`}>
          <span className="text-2xl">{covered ? '✅' : '⚠️'}</span>
          <div>
            <p className={`font-semibold text-sm ${covered ? 'text-green-800' : 'text-red-800'}`}>
              {covered
                ? `SORTA Access paratransit is available here`
                : `Paratransit coverage is uncertain for this neighborhood`}
            </p>
            <p className="text-xs text-gray-600 mt-0.5">
              {stopsNearby !== null
                ? `${stopsNearby} fixed-route bus stop${stopsNearby !== 1 ? 's' : ''} within ¾ mile of neighborhood center`
                : 'Loading…'}
            </p>
          </div>
        </div>

        {/* How this works */}
        <div className="text-sm text-gray-700 space-y-1.5">
          <p>
            Under the <strong>Americans with Disabilities Act (ADA)</strong>, transit agencies must
            offer paratransit service within <strong>¾ mile</strong> of every fixed-route bus line,
            during the same hours. SORTA's service is called <strong>Access</strong>.
          </p>
          <p>
            This calculation uses the neighborhood's geographic center. Individual addresses near
            the neighborhood boundary may have different coverage — use{' '}
            <a
              href="https://www.go-metro.com/riding-metro/accessibility/access"
              target="_blank"
              rel="noopener noreferrer"
              className="text-[#1A4A6B] underline"
            >
              SORTA's Access eligibility tool
            </a>{' '}
            to check a specific address.
          </p>
        </div>

        {/* Data gap callout */}
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 text-xs text-amber-800 space-y-1">
          <p className="font-semibold">📊 Data we don't have yet</p>
          <p>
            SORTA's GTFS feed includes a <code>wheelchair_boarding</code> field indicating which
            stops have accessible boarding. Our current stops file was built without it — this
            score currently reflects stop proximity only, not confirmed accessibility at each stop.
          </p>
          <p>
            <a
              href="https://www.go-metro.com/about/developer-data/"
              target="_blank"
              rel="noopener noreferrer"
              className="underline font-medium"
            >
              View SORTA's open developer data →
            </a>
          </p>
        </div>
      </div>
    </DataCard>
  );
}

/**
 * Data gaps & call-to-action section — the most important part of this tab.
 * Frames missing data as a civic call-to-action, not just an error state.
 */
function DataGapsCard({ view }: { view: ImpairmentView }) {
  type Gap = { what: string; who: string; link?: string; linkLabel?: string };

  const gaps: Record<ImpairmentView, Gap[]> = {
    overview: [
      {
        what: 'Real-time disability services directory — Ohio DODD maintains a provider directory but does not publish it as a queryable open dataset.',
        who: 'Ohio Department of Developmental Disabilities',
        link: 'https://dodd.ohio.gov',
        linkLabel: 'dodd.ohio.gov',
      },
      {
        what: 'SSA SSDI/SSI recipient counts by ZIP code — publicly reported in aggregate but not available as a real-time API.',
        who: 'Social Security Administration',
        link: 'https://www.ssa.gov/policy/docs/statcomps/',
        linkLabel: 'SSA Annual Statistical Supplement',
      },
    ],
    mobility: [
      {
        what: "Curb cut and sidewalk ramp inventory — Cincinnati has no published open dataset of ADA curb cuts. The city's ADA Transition Plan exists but condition data is not machine-readable.",
        who: 'City of Cincinnati — ADA Coordinator & Public Services',
        link: 'https://www.cincinnati-oh.gov/ada/',
        linkLabel: 'Cincinnati ADA Office',
      },
      {
        what: 'Sidewalk condition ratings — Hamilton County and the City of Cincinnati have not published a machine-readable sidewalk condition survey.',
        who: 'Cincinnati City Council & Hamilton County Commissioners',
      },
      {
        what: 'Accessible parking enforcement records — Available internally to the city but not published as open data.',
        who: 'City of Cincinnati — Parking & Revenue',
      },
      {
        what: 'SORTA Access trip volume by neighborhood — SORTA collects operational data but does not publish ridership by neighborhood.',
        who: 'SORTA Board of Trustees',
        link: 'https://www.go-metro.com/about/board-of-trustees/',
        linkLabel: 'SORTA Board contact',
      },
    ],
    vision: [
      {
        what: 'Audible pedestrian signal (APS) locations — Cincinnati has no published inventory of intersections with audible walk signals.',
        who: 'City of Cincinnati — Traffic Engineering',
        link: 'https://www.cincinnati-oh.gov/pworks/',
        linkLabel: 'Public Services Department',
      },
      {
        what: 'Tactile (detectable warning) surface inventory — no open dataset exists for tactile paving at Cincinnati crosswalks.',
        who: 'City of Cincinnati — ADA Coordinator',
        link: 'https://www.cincinnati-oh.gov/ada/',
        linkLabel: 'Cincinnati ADA Office',
      },
    ],
    hearing: [
      {
        what: 'Visual alert infrastructure locations (visual fire alarms, TTY devices at public facilities) — no public dataset exists.',
        who: 'City of Cincinnati — ADA Coordinator',
        link: 'https://www.cincinnati-oh.gov/ada/',
        linkLabel: 'Cincinnati ADA Office',
      },
      {
        what: 'ASL interpreter availability at city services — not published as open data.',
        who: 'City of Cincinnati — Human Services',
      },
    ],
    cognitive: [
      {
        what: 'Community mental health center locations and capacity — ADAMHS Board publishes a provider directory but not as a structured open dataset.',
        who: 'ADAMHS Board of Hamilton County',
        link: 'https://www.adamhs.org/',
        linkLabel: 'ADAMHS Board',
      },
      {
        what: 'Group home and supported living facility locations — Ohio DODD maintains licensing data that is not published as open data.',
        who: 'Ohio Department of Developmental Disabilities',
        link: 'https://dodd.ohio.gov',
        linkLabel: 'Ohio DODD',
      },
    ],
  };

  const currentGaps = gaps[view] ?? [];

  return (
    <div className="bg-white rounded-lg shadow-sm border border-blue-200 p-5 mb-4">
      {/* Header */}
      <div className="flex items-start gap-3 mb-4">
        <div className="text-2xl">📣</div>
        <div>
          <h3 className="text-base font-bold text-[#1A4A6B]">
            This data should be public — here's how to make it happen
          </h3>
          <p className="text-sm text-gray-600 mt-1">
            The gaps below represent real barriers for Cincinnati's disabled community.
            Each one is a request that a resident, advocate, or council member can make right now.
          </p>
        </div>
      </div>

      {/* Gap list */}
      <div className="space-y-3">
        {currentGaps.map((gap, i) => (
          <div key={i} className="border border-gray-200 rounded-lg p-3">
            <p className="text-sm text-gray-800">{gap.what}</p>
            <div className="flex items-center justify-between mt-2 flex-wrap gap-2">
              <span className="text-xs text-gray-500 font-medium">
                Ask: <span className="text-gray-700">{gap.who}</span>
              </span>
              {gap.link && (
                <a
                  href={gap.link}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-xs text-[#1A4A6B] underline font-medium"
                >
                  {gap.linkLabel ?? gap.link} →
                </a>
              )}
            </div>
          </div>
        ))}
      </div>

      {/* Universal call to action */}
      <div className="mt-4 pt-4 border-t border-gray-200 text-xs text-gray-600 space-y-1.5">
        <p className="font-semibold text-gray-700">Want to help fill these gaps?</p>
        <div className="flex flex-wrap gap-3">
          <a
            href="https://www.cincinnati-oh.gov/citycouncil/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#1A4A6B] underline"
          >
            Cincinnati City Council →
          </a>
          <a
            href="https://data.cincinnati-oh.gov"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#1A4A6B] underline"
          >
            Request data on Cincinnati Open Data →
          </a>
          <a
            href="https://github.com/chanfriendly/cincinnati-civic-data"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#1A4A6B] underline"
          >
            Contribute to this project →
          </a>
        </div>
      </div>
    </div>
  );
}

// ── Main views ────────────────────────────────────────────────────────────────

function OverviewView({
  stats,
  neighborhood,
}: {
  stats: NeighborhoodDisabilityStats | null;
  neighborhood: string;
}) {
  if (!stats) {
    return (
      <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mb-4 text-sm text-amber-800">
        <p className="font-semibold">Census disability data not yet loaded</p>
        <p className="mt-1">
          Run <code className="bg-amber-100 px-1 rounded">python3 scripts/build_disability.py</code>{' '}
          locally to generate <code className="bg-amber-100 px-1 rounded">public/data/neighborhood_disability.json</code>,
          then commit and redeploy.
        </p>
      </div>
    );
  }

  const anyPct = pct(stats.anyDisability, stats.pop);

  return (
    <div className="space-y-4">
      {/* Key metrics */}
      <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 mb-2">
        <StatCallout
          value={anyPct !== null ? formatPercent(anyPct) : 'N/A'}
          label="with a disability"
          sub="any type"
          colorClass={anyPct !== null ? rateColor(anyPct) : 'bg-gray-50 text-gray-700'}
        />
        <StatCallout
          value={stats.pop.toLocaleString()}
          label="total population"
          sub="civilian, non-institutionalized"
          colorClass="bg-blue-50 text-[#1A4A6B]"
        />
        <StatCallout
          value={
            stats.disabilityTotal > 0
              ? formatPercent(pct(stats.disabilityPoverty, stats.disabilityTotal) ?? 0)
              : 'N/A'
          }
          label="disabled + below poverty"
          sub="federal poverty level"
          colorClass={
            stats.disabilityTotal > 0 && pct(stats.disabilityPoverty, stats.disabilityTotal)! > 25
              ? 'bg-red-50 text-red-700'
              : 'bg-blue-50 text-[#1A4A6B]'
          }
        />
      </div>

      {/* By disability type */}
      <DataCard
        title="Disability Types — Population Breakdown"
        attribution={{ datasetName: 'ACS 5-Year 2022 — B18102–B18107', lastUpdated: null, uid: 'census-acs' }}
      >
        <div className="mb-3 text-xs text-gray-500 bg-gray-50 rounded p-2">
          People may have more than one disability type; totals may exceed the "any disability" count.
          ACS data is survey-based — small neighborhoods have wider margins of error.
        </div>
        {statRow('Any disability', anyPct !== null ? formatPercent(anyPct) : 'N/A', `~${stats.anyDisability.toLocaleString()} people`)}
        {statRow('Ambulatory (mobility) difficulty', pct(stats.ambulatory, stats.pop) !== null ? formatPercent(pct(stats.ambulatory, stats.pop)!) : 'N/A', `~${stats.ambulatory.toLocaleString()} people`)}
        {statRow('Cognitive difficulty', pct(stats.cognitive, stats.pop) !== null ? formatPercent(pct(stats.cognitive, stats.pop)!) : 'N/A', `~${stats.cognitive.toLocaleString()} people`)}
        {statRow('Independent living difficulty', pct(stats.independentLiving, stats.pop) !== null ? formatPercent(pct(stats.independentLiving, stats.pop)!) : 'N/A', `~${stats.independentLiving.toLocaleString()} people`)}
        {statRow('Self-care difficulty', pct(stats.selfCare, stats.pop) !== null ? formatPercent(pct(stats.selfCare, stats.pop)!) : 'N/A', `~${stats.selfCare.toLocaleString()} people`)}
        {statRow('Hearing difficulty', pct(stats.hearing, stats.pop) !== null ? formatPercent(pct(stats.hearing, stats.pop)!) : 'N/A', `~${stats.hearing.toLocaleString()} people`)}
        {statRow('Vision difficulty', pct(stats.vision, stats.pop) !== null ? formatPercent(pct(stats.vision, stats.pop)!) : 'N/A', `~${stats.vision.toLocaleString()} people`)}
      </DataCard>

      {/* Poverty crosswalk */}
      <DataCard
        title="Economic Vulnerability"
        attribution={{ datasetName: 'ACS 5-Year 2022 — C18130', lastUpdated: null }}
      >
        <p className="text-sm text-gray-600 mb-3">
          People with disabilities face significantly higher rates of poverty nationwide.
          This section shows the intersection in {neighborhood}.
        </p>
        {statRow(
          'Disabled residents below poverty line',
          stats.disabilityTotal > 0
            ? formatPercent(pct(stats.disabilityPoverty, stats.disabilityTotal) ?? 0)
            : 'N/A',
          'As a share of all residents with a disability'
        )}
        <div className="mt-3 text-xs text-gray-500 bg-yellow-50 border border-yellow-100 rounded p-2">
          For reference: the national disability poverty rate is approximately 25–28% (ACS 2022).
          Rates above 30% indicate concentrated economic hardship in this community.
        </div>
      </DataCard>
    </div>
  );
}

function MobilityView({
  stats,
  neighborhood,
}: {
  stats: NeighborhoodDisabilityStats | null;
  neighborhood: string;
}) {
  const ambulatoryPct = stats ? pct(stats.ambulatory, stats.pop) : null;

  return (
    <div className="space-y-4">
      {/* Key metric */}
      {stats && (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <StatCallout
            value={ambulatoryPct !== null ? formatPercent(ambulatoryPct) : 'N/A'}
            label="ambulatory difficulty"
            sub="mobility impairment — ACS B18105"
            colorClass={ambulatoryPct !== null ? rateColor(ambulatoryPct) : 'bg-gray-50 text-gray-700'}
          />
          <StatCallout
            value={stats.ambulatory.toLocaleString()}
            label="residents with mobility limitations"
            sub="civilian non-institutionalized"
            colorClass="bg-blue-50 text-[#1A4A6B]"
          />
        </div>
      )}

      {!stats && (
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 text-sm text-amber-800">
          Census mobility data will appear here after running{' '}
          <code className="bg-amber-100 px-1 rounded">scripts/build_disability.py</code>.
        </div>
      )}

      {/* ADA paratransit */}
      <ParatransitCard neighborhood={neighborhood} />

      {/* OSM infrastructure — future */}
      <DataCard title="Pedestrian Infrastructure (Coming Soon)">
        <div className="text-sm text-gray-600 space-y-2">
          <p>
            We are working to integrate <strong>OpenStreetMap</strong> data on curb cuts,
            wheelchair-accessible paths, and accessible parking in Cincinnati.
          </p>
          <p>
            OpenStreetMap is community-maintained — mapping quality varies by neighborhood.
            Well-mapped areas may appear more accessible simply because more volunteers have
            documented them. We will make this caveat prominent when the data is live.
          </p>
          <div className="flex gap-3 flex-wrap mt-3 text-xs">
            <a
              href="https://www.openstreetmap.org/#map=13/39.1031/-84.5120"
              target="_blank"
              rel="noopener noreferrer"
              className="text-[#1A4A6B] underline"
            >
              Help map Cincinnati accessibility on OSM →
            </a>
          </div>
        </div>
      </DataCard>

      {/* CMS care facilities — future */}
      <DataCard title="Nearby Care & Support Facilities (Coming Soon)">
        <div className="text-sm text-gray-600 space-y-2">
          <p>
            This section will show <strong>nursing homes, home health agencies, and rehabilitation
            facilities</strong> near {neighborhood} using CMS Care Compare data — a free federal
            dataset with quality ratings.
          </p>
          <a
            href="https://www.medicare.gov/care-compare/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-xs text-[#1A4A6B] underline"
          >
            View CMS Care Compare directly →
          </a>
        </div>
      </DataCard>
    </div>
  );
}

function VisionView({ stats }: { stats: NeighborhoodDisabilityStats | null }) {
  const visionPct = stats ? pct(stats.vision, stats.pop) : null;

  return (
    <div className="space-y-4">
      {stats && (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <StatCallout
            value={visionPct !== null ? formatPercent(visionPct) : 'N/A'}
            label="vision difficulty"
            sub="ACS B18103"
            colorClass={visionPct !== null ? rateColor(visionPct) : 'bg-gray-50 text-gray-700'}
          />
          <StatCallout
            value={stats.vision.toLocaleString()}
            label="residents with vision impairment"
            colorClass="bg-blue-50 text-[#1A4A6B]"
          />
        </div>
      )}

      {!stats && (
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 text-sm text-amber-800">
          Census vision data will appear here after running{' '}
          <code className="bg-amber-100 px-1 rounded">scripts/build_disability.py</code>.
        </div>
      )}

      <DataCard title="Accessible Pedestrian Signals & Tactile Infrastructure (Coming Soon)">
        <div className="text-sm text-gray-600 space-y-2">
          <p>
            Audible pedestrian signals (APS) and tactile detectable warning surfaces are critical
            infrastructure for blind and low-vision residents. Cincinnati does not yet publish an
            open inventory of these installations.
          </p>
          <p>
            OpenStreetMap community tagging (<code>tactile_paving=yes</code>,{' '}
            <code>traffic_signals:sound=yes</code>) can partially fill this gap.
          </p>
        </div>
      </DataCard>

      <DataCard title="Local Vision Support Organizations">
        <div className="text-sm text-gray-700 space-y-3">
          {[
            {
              name: 'Cincinnati Association for the Blind and Visually Impaired (CABVI)',
              url: 'https://www.cabvi.org',
              desc: 'Provides rehabilitation, employment, and community services for people who are blind or have low vision in the Cincinnati region.',
            },
            {
              name: 'Ohio Library for the Blind and Print Disabled (via OPLIN)',
              url: 'https://library.ohio.gov/services-for-libraries/library-programs-development/accessible-reading/',
              desc: 'Free talking books, braille, and accessible formats for Ohioans who cannot read standard print.',
            },
          ].map((org) => (
            <div key={org.name} className="border border-gray-100 rounded p-3">
              <a
                href={org.url}
                target="_blank"
                rel="noopener noreferrer"
                className="text-[#1A4A6B] font-medium text-sm underline"
              >
                {org.name}
              </a>
              <p className="text-xs text-gray-600 mt-1">{org.desc}</p>
            </div>
          ))}
        </div>
      </DataCard>
    </div>
  );
}

function HearingView({ stats }: { stats: NeighborhoodDisabilityStats | null }) {
  const hearingPct = stats ? pct(stats.hearing, stats.pop) : null;

  return (
    <div className="space-y-4">
      {stats && (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <StatCallout
            value={hearingPct !== null ? formatPercent(hearingPct) : 'N/A'}
            label="hearing difficulty"
            sub="ACS B18102"
            colorClass={hearingPct !== null ? rateColor(hearingPct) : 'bg-gray-50 text-gray-700'}
          />
          <StatCallout
            value={stats.hearing.toLocaleString()}
            label="residents with hearing impairment"
            colorClass="bg-blue-50 text-[#1A4A6B]"
          />
        </div>
      )}

      {!stats && (
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 text-sm text-amber-800">
          Census hearing data will appear here after running{' '}
          <code className="bg-amber-100 px-1 rounded">scripts/build_disability.py</code>.
        </div>
      )}

      <DataCard title="Public Communication Infrastructure">
        <div className="text-sm text-gray-600 space-y-2">
          <p>
            Visual alert systems, TTY/TDD availability at government offices, and ASL interpretation
            at public meetings are important for Deaf and hard-of-hearing residents. Cincinnati does
            not currently publish this as open data.
          </p>
          <p>
            The ADA requires city services to provide effective communication access on request.
            If you have encountered a barrier, you can file a complaint with the{' '}
            <a
              href="https://www.cincinnati-oh.gov/ada/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-[#1A4A6B] underline"
            >
              City of Cincinnati ADA Coordinator
            </a>.
          </p>
        </div>
      </DataCard>

      <DataCard title="Local Deaf & Hard-of-Hearing Organizations">
        <div className="text-sm text-gray-700 space-y-3">
          {[
            {
              name: 'Hearing, Speech & Deaf Center of Greater Cincinnati',
              url: 'https://www.hsdcgc.org',
              desc: 'Provides audiological, speech-language, and Deaf services across the Greater Cincinnati region.',
            },
            {
              name: 'Ohio School for the Deaf Alumni Association',
              url: 'https://www.ohioschoolforthedeaf.org',
              desc: 'Community connection and advocacy for the Deaf community in Ohio.',
            },
          ].map((org) => (
            <div key={org.name} className="border border-gray-100 rounded p-3">
              <a
                href={org.url}
                target="_blank"
                rel="noopener noreferrer"
                className="text-[#1A4A6B] font-medium text-sm underline"
              >
                {org.name}
              </a>
              <p className="text-xs text-gray-600 mt-1">{org.desc}</p>
            </div>
          ))}
        </div>
      </DataCard>
    </div>
  );
}

function CognitiveView({ stats }: { stats: NeighborhoodDisabilityStats | null }) {
  const cognitivePct = stats ? pct(stats.cognitive, stats.pop) : null;
  const independentPct = stats ? pct(stats.independentLiving, stats.pop) : null;

  return (
    <div className="space-y-4">
      {stats && (
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          <StatCallout
            value={cognitivePct !== null ? formatPercent(cognitivePct) : 'N/A'}
            label="cognitive difficulty"
            sub="ACS B18104"
            colorClass={cognitivePct !== null ? rateColor(cognitivePct) : 'bg-gray-50 text-gray-700'}
          />
          <StatCallout
            value={independentPct !== null ? formatPercent(independentPct) : 'N/A'}
            label="independent living difficulty"
            sub="ACS B18107"
            colorClass={independentPct !== null ? rateColor(independentPct) : 'bg-gray-50 text-gray-700'}
          />
          <StatCallout
            value={stats ? pct(stats.selfCare, stats.pop) !== null ? formatPercent(pct(stats.selfCare, stats.pop)!) : 'N/A' : 'N/A'}
            label="self-care difficulty"
            sub="ACS B18106"
            colorClass="bg-blue-50 text-[#1A4A6B]"
          />
        </div>
      )}

      {!stats && (
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 text-sm text-amber-800">
          Census cognitive data will appear here after running{' '}
          <code className="bg-amber-100 px-1 rounded">scripts/build_disability.py</code>.
        </div>
      )}

      <DataCard title="Mental Health & Developmental Disability Services">
        <div className="text-sm text-gray-600 space-y-2">
          <p>
            This section will show nearby <strong>community mental health centers, supported living
            facilities, and developmental disability service providers</strong> when those datasets
            become available as open data.
          </p>
          <div className="mt-3 space-y-2">
            <p className="font-medium text-gray-700 text-xs">Available now:</p>
            {[
              {
                label: 'ADAMHS Board of Hamilton County — Community mental health services directory',
                href: 'https://www.adamhs.org/finding-help/',
              },
              {
                label: 'Ohio Department of Developmental Disabilities — County board locator',
                href: 'https://dodd.ohio.gov/county-boards',
              },
              {
                label: 'Hamilton County DD Services',
                href: 'https://hcdd.org',
              },
            ].map((r) => (
              <a
                key={r.href}
                href={r.href}
                target="_blank"
                rel="noopener noreferrer"
                className="block text-xs text-[#1A4A6B] underline"
              >
                {r.label} →
              </a>
            ))}
          </div>
        </div>
      </DataCard>
    </div>
  );
}

// ── Main component ────────────────────────────────────────────────────────────

export default function Accessibility() {
  useTranslation(); // keep i18n context available for future string keys
  const [selectedNeighborhood, setSelectedNeighborhood] = useState<string>(NEIGHBORHOODS[0]);
  const [activeView, setActiveView] = useState<ImpairmentView>('overview');
  const [disabilityMap, setDisabilityMap] = useState<Map<string, NeighborhoodDisabilityStats>>(new Map());
  const [loadingStats, setLoadingStats] = useState(true);
  const [statsError, setStatsError] = useState<string | null>(null);

  // Load disability stats once on mount
  useEffect(() => {
    setLoadingStats(true);
    fetchNeighborhoodDisabilityStats()
      .then(setDisabilityMap)
      .catch((e) => setStatsError(String(e)))
      .finally(() => setLoadingStats(false));
  }, []);

  const stats = useMemo((): NeighborhoodDisabilityStats | null => {
    if (loadingStats || disabilityMap.size === 0) return null;
    const key = stripNeighborhoodName(selectedNeighborhood);
    return disabilityMap.get(key) ?? null;
  }, [disabilityMap, selectedNeighborhood, loadingStats]);

  return (
    <div className="space-y-6">
      {/* Page header */}
      <div>
        <h1 className="text-2xl font-bold text-[#1A4A6B]">♿ Accessibility Resource Center</h1>
        <p className="text-gray-600 mt-1 text-sm">
          Disability demographics, transit coverage, and infrastructure data for Cincinnati neighborhoods.
          Use the impairment type selector to focus on what matters to you.
        </p>
      </div>

      {/* Controls: neighborhood + view selector */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-100 p-4 space-y-4">
        {/* Neighborhood selector */}
        <div className="flex flex-col sm:flex-row gap-3 items-start sm:items-center">
          <label htmlFor="acc-neighborhood" className="text-sm font-medium text-gray-700 shrink-0">
            Neighborhood
          </label>
          <select
            id="acc-neighborhood"
            value={selectedNeighborhood}
            onChange={(e) => setSelectedNeighborhood(e.target.value)}
            className="w-full sm:w-auto border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#1A4A6B] bg-white"
          >
            {NEIGHBORHOODS.map((n) => (
              <option key={n} value={n}>{n}</option>
            ))}
          </select>
          {loadingStats && (
            <span className="text-xs text-gray-500 animate-pulse">Loading disability data…</span>
          )}
          {statsError && (
            <span className="text-xs text-red-500">{statsError}</span>
          )}
        </div>

        {/* Impairment view pills */}
        <div>
          <p className="text-xs font-medium text-gray-500 mb-2">View by impairment type</p>
          <div className="flex flex-wrap gap-2">
            {VIEWS.map((view) => (
              <button
                key={view.id}
                onClick={() => setActiveView(view.id)}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full text-sm font-medium transition-colors border ${
                  activeView === view.id
                    ? 'bg-[#1A4A6B] text-white border-[#1A4A6B]'
                    : 'bg-white text-gray-700 border-gray-300 hover:border-[#1A4A6B] hover:text-[#1A4A6B]'
                }`}
                title={view.description}
              >
                <span>{view.icon}</span>
                <span>{view.label}</span>
              </button>
            ))}
          </div>
          <p className="text-xs text-gray-500 mt-2 italic">
            {VIEWS.find((v) => v.id === activeView)?.description}
          </p>
        </div>
      </div>

      {/* Active view content */}
      <div>
        {activeView === 'overview' && (
          <OverviewView stats={stats} neighborhood={selectedNeighborhood} />
        )}
        {activeView === 'mobility' && (
          <MobilityView stats={stats} neighborhood={selectedNeighborhood} />
        )}
        {activeView === 'vision' && (
          <VisionView stats={stats} />
        )}
        {activeView === 'hearing' && (
          <HearingView stats={stats} />
        )}
        {activeView === 'cognitive' && (
          <CognitiveView stats={stats} />
        )}
      </div>

      {/* Data gaps call to action — always shown at bottom */}
      <DataGapsCard view={activeView} />

      {/* ACS data note */}
      <div className="text-xs text-gray-500 bg-gray-50 rounded-lg p-3 space-y-1">
        <p className="font-medium text-gray-600">About this data</p>
        <p>
          Disability statistics are from the <strong>U.S. Census American Community Survey
          5-Year estimates (2022)</strong>, table series B18101–B18107 and C18130.
          ACS data is survey-based — estimates for small neighborhoods carry wider margins of error.
          Neighborhood boundaries use Cincinnati's Statistical Neighborhood Approximations (SNAs);
          census tract boundaries don't align perfectly and some ambiguous tracts are attributed
          to their nearest neighborhood centroid.
        </p>
        <p>
          <a
            href="https://www.census.gov/programs-surveys/acs/data.html"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#1A4A6B] underline"
          >
            U.S. Census ACS →
          </a>
          {' · '}
          <a
            href="https://censusreporter.org/tables/B18101/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#1A4A6B] underline"
          >
            Explore disability tables on Census Reporter →
          </a>
        </p>
      </div>
    </div>
  );
}
