/**
 * Accessibility Tab — Cincinnati Civic Data Platform
 *
 * Shows disability demographics, transit/paratransit coverage, and infrastructure
 * data for each Cincinnati neighborhood, with adjustable views by impairment type.
 *
 * Data sources:
 *   - Census ACS 5-Year 2022  → public/data/neighborhood_disability.json (pre-built)
 *   - SORTA GTFS               → public/data/sorta_stops.json (already loaded in Tab 1)
 *
 * The Census disability data file is generated by running:
 *   python3 scripts/build_disability.py
 * (Must be run locally — Census API is blocked from Cowork sandbox.)
 *
 * Planned additions (future sessions):
 *   - OpenStreetMap Overpass: curb cuts, wheelchair-accessible paths, accessible parking
 *   - CMS Care Compare: nursing homes, home health agencies, dialysis centers
 *   - SORTA GTFS wheelchair_boarding field (requires re-importing stops with accessibility flags)
 */

import { useState, useEffect, useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import {
  fetchNeighborhoodDisabilityStats,
  distanceMiles,
  stripNeighborhoodName,
  formatPercent,
} from '../../utils/api';
import type { NeighborhoodDisabilityStats } from '../../types';
import { DataCard } from '../../components/ui';
import { C } from '../../components/ui/DesignAtoms';

// ── Neighborhood list (matches Tab 2 — CPD SNA names) ────────────────────────

const NEIGHBORHOODS = [
  'Avondale', 'Bond Hill', 'California', 'Camp Washington', 'Carthage',
  'CBD / Riverfront', 'Clifton', 'Clifton Heights', 'College Hill',
  'Columbia-Tusculum', 'Corryville', 'East End', 'East Price Hill',
  'East Walnut Hills', 'East Westwood', 'English Woods', 'Evanston',
  'Fairview', 'Fay Apartments', 'Hartwell', 'Hyde Park', 'Kennedy Heights',
  'Linwood', 'Lower Price Hill', 'Madisonville', 'Millvale', 'Mount Adams',
  'Mount Airy', 'Mount Auburn', 'Mt. Lookout', 'Mt. Washington',
  'North Avondale', 'North Fairmount', 'Northside', 'Oakley', "O'Bryonville",
  'Over-the-Rhine', 'Paddock Hills', 'Pendleton', 'Pleasant Ridge', 'Queensgate',
  'Riverside', 'Roselawn', 'Sayler Park', 'Sedamsville', 'South Cumminsville',
  'South Fairmount', 'Spring Grove Village', 'Walnut Hills', 'West End',
  'West Price Hill', 'Westwood', 'Winton Hills',
];

// SORTA paratransit: ADA requires Access service within 3/4 mile of any fixed-route stop.
const ADA_PARATRANSIT_RADIUS_MILES = 0.75;

// Approximate neighborhood centroids used for paratransit coverage computation.
// These mirror the closest-centroid assignments in the Census build pipeline.
// Long-term: derive from the SNA GeoJSON centroids directly.
const NEIGHBORHOOD_CENTROIDS: Record<string, [number, number]> = {
  'Avondale':           [39.1312, -84.5009],
  'Bond Hill':          [39.1756, -84.4742],
  'California':         [39.0911, -84.4527],
  'Camp Washington':    [39.1217, -84.5369],
  'Carthage':           [39.1879, -84.4800],
  'CBD / Riverfront':   [39.1031, -84.5120],
  'Clifton':            [39.1440, -84.5178],
  'Clifton Heights':    [39.1298, -84.5235],
  'College Hill':       [39.1977, -84.5243],
  'Columbia-Tusculum':  [39.1037, -84.4561],
  'Corryville':         [39.1330, -84.5135],
  'East End':           [39.0950, -84.4368],
  'East Price Hill':    [39.1026, -84.5399],
  'East Walnut Hills':  [39.1252, -84.4873],
  'East Westwood':      [39.1433, -84.5688],
  'English Woods':      [39.1699, -84.5599],
  'Evanston':           [39.1453, -84.4898],
  'Fairview':           [39.1350, -84.5253],
  'Fay Apartments':     [39.1060, -84.5250],
  'Hartwell':           [39.2023, -84.5182],
  'Hyde Park':          [39.1434, -84.4558],
  'Kennedy Heights':    [39.1767, -84.4548],
  'Linwood':            [39.1079, -84.4708],
  'Lower Price Hill':   [39.1113, -84.5530],
  'Madisonville':       [39.1483, -84.4368],
  'Millvale':           [39.1244, -84.5548],
  'Mount Adams':        [39.1107, -84.4976],
  'Mount Airy':         [39.1803, -84.5488],
  'Mount Auburn':       [39.1179, -84.5054],
  'Mt. Lookout':        [39.1259, -84.4368],
  'Mt. Washington':     [39.0882, -84.4523],
  'North Avondale':     [39.1589, -84.4951],
  'North Fairmount':    [39.1443, -84.5546],
  'Northside':          [39.1607, -84.5358],
  'Oakley':             [39.1478, -84.4618],
  "O'Bryonville":       [39.1370, -84.4542],
  'Over-the-Rhine':     [39.1125, -84.5175],
  'Paddock Hills':      [39.1885, -84.4882],
  'Pendleton':          [39.1095, -84.5076],
  'Pleasant Ridge':     [39.1665, -84.4492],
  'Queensgate':         [39.1098, -84.5322],
  'Riverside':          [39.0917, -84.5142],
  'Roselawn':           [39.1725, -84.4714],
  'Sayler Park':        [39.0938, -84.6007],
  'Sedamsville':        [39.0980, -84.5775],
  'South Cumminsville': [39.1326, -84.5558],
  'South Fairmount':    [39.1199, -84.5493],
  'Spring Grove Village':[39.1612, -84.5536],
  'Walnut Hills':       [39.1300, -84.4885],
  'West End':           [39.1115, -84.5283],
  'West Price Hill':    [39.1152, -84.5666],
  'Westwood':           [39.1470, -84.5818],
  'Winton Hills':       [39.1927, -84.5026],
};

// ── Impairment view types ─────────────────────────────────────────────────────

type ImpairmentView = 'overview' | 'mobility' | 'vision' | 'hearing' | 'cognitive';

interface ViewConfig {
  id: ImpairmentView;
  label: string;
  icon: React.ReactNode;
  description: string;
}

// SVG icons replacing raw emoji
const IconAccessibility = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="12" cy="4" r="2"/>
    <path d="M12 6v6l4 2M8 8h8"/>
    <path d="M9 20a3 3 0 106 0"/>
  </svg>
);
const IconMobility = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="12" cy="5" r="2"/>
    <path d="M8 11h8l-1 7H9l-1-7z"/>
    <path d="M9 18l-1 4M15 18l1 4"/>
  </svg>
);
const IconVision = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/>
    <path d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/>
  </svg>
);
const IconHearing = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M15.536 8.464a5 5 0 010 7.072"/>
    <path d="M12 6a7 7 0 010 12"/>
    <path d="M9 10a3 3 0 000 4"/>
  </svg>
);
const IconCognitive = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <circle cx="12" cy="12" r="9"/>
    <path d="M9 9h.01M15 9h.01M9.5 14a3.5 3.5 0 005 0"/>
  </svg>
);
const IconCheck = () => (
  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
    <path d="M5 13l4 4L19 7"/>
  </svg>
);
const IconWarning = () => (
  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M12 9v4m0 4h.01M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z"/>
  </svg>
);
const IconMegaphone = () => (
  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M3 11l19-9-9 19-2-8-8-2z"/>
  </svg>
);
const IconBarChart = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <rect x="3" y="12" width="4" height="9"/><rect x="10" y="7" width="4" height="14"/><rect x="17" y="3" width="4" height="18"/>
  </svg>
);

const VIEWS: ViewConfig[] = [
  {
    id: 'overview',
    label: 'All Disabilities',
    icon: <IconAccessibility />,
    description: 'Population-level disability demographics, poverty crosswalk, and earnings gap.',
  },
  {
    id: 'mobility',
    label: 'Mobility & Physical',
    icon: <IconMobility />,
    description: 'Ambulatory difficulty, ADA paratransit coverage, and accessible transit.',
  },
  {
    id: 'vision',
    label: 'Vision',
    icon: <IconVision />,
    description: 'Vision difficulty rates and infrastructure relevant to the visually impaired.',
  },
  {
    id: 'hearing',
    label: 'Hearing',
    icon: <IconHearing />,
    description: 'Hearing difficulty rates and relevant community context.',
  },
  {
    id: 'cognitive',
    label: 'Cognitive & Independent Living',
    icon: <IconCognitive />,
    description: 'Cognitive difficulty and independent living difficulty rates.',
  },
];

// ── Helpers ──────────────────────────────────────────────────────────────────

function pct(numerator: number, denominator: number): number | null {
  if (!denominator) return null;
  return (numerator / denominator) * 100;
}

function statRow(label: string, value: string | null, note?: string) {
  return (
    <div className="flex justify-between items-start py-2 border-b last:border-0" style={{ borderColor: C.rule }}>
      <div>
        <span className="text-sm" style={{ color: C.ink }}>{label}</span>
        {note && <p className="text-xs mt-0.5" style={{ color: C.muted }}>{note}</p>}
      </div>
      <span className="text-sm font-semibold ml-4 shrink-0" style={{ color: C.river }}>
        {value ?? 'N/A'}
      </span>
    </div>
  );
}

// Color scale for disability rates: green (low) → yellow → red (high)
// Returns a style object instead of Tailwind class strings
function rateStyle(rate: number): React.CSSProperties {
  if (rate < 10) return { color: C.hill, background: C.hillLight };
  if (rate < 18) return { color: C.ochre, background: C.limestone };
  return { color: C.brick, background: C.brickLight };
}

// ── SORTA paratransit helpers ─────────────────────────────────────────────────

interface SORTAStop {
  stop_lat: number;
  stop_lon: number;
  stop_name: string;
  routes: string[];
}

async function loadSORTAStops(): Promise<SORTAStop[]> {
  const resp = await fetch('/data/sorta_stops.json');
  if (!resp.ok) throw new Error('SORTA stops unavailable');
  return resp.json();
}

// ── Sub-components ────────────────────────────────────────────────────────────

/** Big stat callout used in each view's key metrics section */
function StatCallout({
  value,
  label,
  sub,
  rateStyles,
}: {
  value: string;
  label: string;
  sub?: string;
  rateStyles?: React.CSSProperties;
}) {
  const containerStyle: React.CSSProperties = {
    background: rateStyles?.background ?? C.riverLight,
    borderRadius: 6,
    padding: '1rem',
    textAlign: 'center',
  };
  const numColor = rateStyles?.color ?? C.riverDeep;

  return (
    <div style={containerStyle}>
      <div className="serif font-medium tnum" style={{ fontSize: 36, color: numColor, lineHeight: 1 }}>{value}</div>
      <div className="text-sm font-medium mt-1" style={{ color: C.ink }}>{label}</div>
      {sub && <div className="text-xs mt-0.5" style={{ color: C.muted }}>{sub}</div>}
    </div>
  );
}

/**
 * Paratransit coverage card — computes ADA Access coverage from SORTA stops.
 * The ADA requires complementary paratransit within 3/4 mile of any fixed route.
 */
function ParatransitCard({ neighborhood }: { neighborhood: string }) {
  const [stopsNearby, setStopsNearby] = useState<number | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const centroid = NEIGHBORHOOD_CENTROIDS[neighborhood];

  useEffect(() => {
    if (!centroid) {
      setError('No centroid data for this neighborhood.');
      setLoading(false);
      return;
    }
    setLoading(true);
    setError(null);
    loadSORTAStops()
      .then((stops) => {
        const [lat, lon] = centroid;
        const nearby = stops.filter(
          (s) => distanceMiles(lat, lon, s.stop_lat, s.stop_lon) <= ADA_PARATRANSIT_RADIUS_MILES
        ).length;
        setStopsNearby(nearby);
      })
      .catch((e) => setError(String(e)))
      .finally(() => setLoading(false));
  }, [neighborhood, centroid]);

  const covered = stopsNearby !== null && stopsNearby > 0;

  return (
    <DataCard
      title="ADA Paratransit Coverage (SORTA Access)"
      loading={loading}
      error={error}
      attribution={{ datasetName: 'SORTA GTFS Static Feed', lastUpdated: null, url: 'https://www.go-metro.com/about/developer-data/' }}
    >
      <div className="space-y-3">
        {/* Coverage status */}
        <div
          className="flex items-center gap-3 p-3 rounded-md"
          style={{ background: covered ? C.hillLight : C.brickLight }}
        >
          <span className="shrink-0" style={{ color: covered ? C.hill : C.brick }}>
            {covered ? <IconCheck /> : <IconWarning />}
          </span>
          <div>
            <p className="font-semibold text-sm" style={{ color: covered ? C.hill : C.brick }}>
              {covered
                ? `SORTA Access paratransit is available here`
                : `Paratransit coverage is uncertain for this neighborhood`}
            </p>
            <p className="text-xs mt-0.5" style={{ color: C.muted }}>
              {stopsNearby !== null
                ? `${stopsNearby} fixed-route bus stop${stopsNearby !== 1 ? 's' : ''} within ¾ mile of neighborhood center`
                : 'Loading…'}
            </p>
          </div>
        </div>

        {/* How this works */}
        <div className="text-sm space-y-1.5" style={{ color: C.ink }}>
          <p>
            Under the <strong>Americans with Disabilities Act (ADA)</strong>, transit agencies must
            offer paratransit service within <strong>¾ mile</strong> of every fixed-route bus line,
            during the same hours. SORTA's service is called <strong>Access</strong>.
          </p>
          <p>
            This calculation uses the neighborhood's geographic center. Individual addresses near
            the neighborhood boundary may have different coverage — use{' '}
            <a
              href="https://www.go-metro.com/riding-metro/accessibility/access"
              target="_blank"
              rel="noopener noreferrer"
              style={{ color: C.river }}
              className="underline"
            >
              SORTA's Access eligibility tool
            </a>{' '}
            to check a specific address.
          </p>
        </div>

        {/* Data gap callout */}
        <div
          className="rounded-md p-3 text-xs space-y-1"
          style={{ background: C.limestone, border: `1px solid ${C.rule}`, color: C.muted }}
        >
          <div className="flex items-center gap-1.5 font-semibold" style={{ color: C.ochre }}>
            <IconBarChart />
            <span>Data we don't have yet</span>
          </div>
          <p>
            SORTA's GTFS feed includes a <code>wheelchair_boarding</code> field indicating which
            stops have accessible boarding. Our current stops file was built without it — this
            score currently reflects stop proximity only, not confirmed accessibility at each stop.
          </p>
          <p>
            <a
              href="https://www.go-metro.com/about/developer-data/"
              target="_blank"
              rel="noopener noreferrer"
              className="underline font-medium"
              style={{ color: C.river }}
            >
              View SORTA's open developer data →
            </a>
          </p>
        </div>
      </div>
    </DataCard>
  );
}

/**
 * Data gaps & call-to-action section — the most important part of this tab.
 * Frames missing data as a civic call-to-action, not just an error state.
 */
function DataGapsCard({ view }: { view: ImpairmentView }) {
  type Gap = { what: string; who: string; link?: string; linkLabel?: string };

  const gaps: Record<ImpairmentView, Gap[]> = {
    overview: [
      {
        what: 'Real-time disability services directory — Ohio DODD maintains a provider directory but does not publish it as a queryable open dataset.',
        who: 'Ohio Department of Developmental Disabilities',
        link: 'https://dodd.ohio.gov',
        linkLabel: 'dodd.ohio.gov',
      },
      {
        what: 'SSA SSDI/SSI recipient counts by ZIP code — publicly reported in aggregate but not available as a real-time API.',
        who: 'Social Security Administration',
        link: 'https://www.ssa.gov/policy/docs/statcomps/',
        linkLabel: 'SSA Annual Statistical Supplement',
      },
    ],
    mobility: [
      {
        what: "Curb cut and sidewalk ramp inventory — Cincinnati has no published open dataset of ADA curb cuts. The city's ADA Transition Plan exists but condition data is not machine-readable.",
        who: 'City of Cincinnati — ADA Coordinator & Public Services',
        link: 'https://www.cincinnati-oh.gov/ada/',
        linkLabel: 'Cincinnati ADA Office',
      },
      {
        what: 'Sidewalk condition ratings — Hamilton County and the City of Cincinnati have not published a machine-readable sidewalk condition survey.',
        who: 'Cincinnati City Council & Hamilton County Commissioners',
      },
      {
        what: 'Accessible parking enforcement records — Available internally to the city but not published as open data.',
        who: 'City of Cincinnati — Parking & Revenue',
      },
      {
        what: 'SORTA Access trip volume by neighborhood — SORTA collects operational data but does not publish ridership by neighborhood.',
        who: 'SORTA Board of Trustees',
        link: 'https://www.go-metro.com/about/board-of-trustees/',
        linkLabel: 'SORTA Board contact',
      },
    ],
    vision: [
      {
        what: 'Audible pedestrian signal (APS) locations — Cincinnati has no published inventory of intersections with audible walk signals.',
        who: 'City of Cincinnati — Traffic Engineering',
        link: 'https://www.cincinnati-oh.gov/pworks/',
        linkLabel: 'Public Services Department',
      },
      {
        what: 'Tactile (detectable warning) surface inventory — no open dataset exists for tactile paving at Cincinnati crosswalks.',
        who: 'City of Cincinnati — ADA Coordinator',
        link: 'https://www.cincinnati-oh.gov/ada/',
        linkLabel: 'Cincinnati ADA Office',
      },
    ],
    hearing: [
      {
        what: 'Visual alert infrastructure locations (visual fire alarms, TTY devices at public facilities) — no public dataset exists.',
        who: 'City of Cincinnati — ADA Coordinator',
        link: 'https://www.cincinnati-oh.gov/ada/',
        linkLabel: 'Cincinnati ADA Office',
      },
      {
        what: 'ASL interpreter availability at city services — not published as open data.',
        who: 'City of Cincinnati — Human Services',
      },
    ],
    cognitive: [
      {
        what: 'Community mental health center locations and capacity — ADAMHS Board publishes a provider directory but not as a structured open dataset.',
        who: 'ADAMHS Board of Hamilton County',
        link: 'https://www.adamhs.org/',
        linkLabel: 'ADAMHS Board',
      },
      {
        what: 'Group home and supported living facility locations — Ohio DODD maintains licensing data that is not published as open data.',
        who: 'Ohio Department of Developmental Disabilities',
        link: 'https://dodd.ohio.gov',
        linkLabel: 'Ohio DODD',
      },
    ],
  };

  const currentGaps = gaps[view] ?? [];

  return (
    <div
      className="rounded-md shadow-sm p-5 mb-4 bg-white"
      style={{ border: `1px solid ${C.rule}` }}
    >
      {/* Header */}
      <div className="flex items-start gap-3 mb-4">
        <span className="shrink-0 mt-0.5" style={{ color: C.brick }}>
          <IconMegaphone />
        </span>
        <div>
          <h3 className="text-base font-bold" style={{ color: C.riverDeep }}>
            This data should be public — here's how to make it happen
          </h3>
          <p className="text-sm mt-1" style={{ color: C.muted }}>
            The gaps below represent real barriers for Cincinnati's disabled community.
            Each one is a request that a resident, advocate, or council member can make right now.
          </p>
        </div>
      </div>

      {/* Gap list */}
      <div className="space-y-3">
        {currentGaps.map((gap, i) => (
          <div key={i} className="rounded-md p-3" style={{ border: `1px solid ${C.rule}` }}>
            <p className="text-sm" style={{ color: C.ink }}>{gap.what}</p>
            <div className="flex items-center justify-between mt-2 flex-wrap gap-2">
              <span className="text-xs font-medium" style={{ color: C.muted }}>
                Ask: <span style={{ color: C.ink }}>{gap.who}</span>
              </span>
              {gap.link && (
                <a
                  href={gap.link}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-xs underline font-medium"
                  style={{ color: C.river }}
                >
                  {gap.linkLabel ?? gap.link} →
                </a>
              )}
            </div>
          </div>
        ))}
      </div>

      {/* Universal call to action */}
      <div className="mt-4 pt-4 text-xs space-y-1.5" style={{ borderTop: `1px solid ${C.rule}`, color: C.muted }}>
        <p className="font-semibold" style={{ color: C.ink }}>Want to help fill these gaps?</p>
        <div className="flex flex-wrap gap-3">
          <a
            href="https://www.cincinnati-oh.gov/citycouncil/"
            target="_blank"
            rel="noopener noreferrer"
            className="underline"
            style={{ color: C.river }}
          >
            Cincinnati City Council →
          </a>
          <a
            href="https://data.cincinnati-oh.gov"
            target="_blank"
            rel="noopener noreferrer"
            className="underline"
            style={{ color: C.river }}
          >
            Request data on Cincinnati Open Data →
          </a>
          <a
            href="https://github.com/chanfriendly/cincinnati-civic-data"
            target="_blank"
            rel="noopener noreferrer"
            className="underline"
            style={{ color: C.river }}
          >
            Contribute to this project →
          </a>
        </div>
      </div>
    </div>
  );
}

// ── Main views ────────────────────────────────────────────────────────────────

function OverviewView({
  stats,
  neighborhood,
}: {
  stats: NeighborhoodDisabilityStats | null;
  neighborhood: string;
}) {
  if (!stats) {
    return (
      <div
        className="rounded-md p-4 mb-4 text-sm"
        style={{ background: C.limestone, border: `1px solid ${C.rule}`, color: C.ochre }}
      >
        <p className="font-semibold">Census disability data not yet loaded</p>
        <p className="mt-1" style={{ color: C.muted }}>
          Run <code className="px-1 rounded" style={{ background: C.rule }}>python3 scripts/build_disability.py</code>{' '}
          locally to generate <code className="px-1 rounded" style={{ background: C.rule }}>public/data/neighborhood_disability.json</code>,
          then commit and redeploy.
        </p>
      </div>
    );
  }

  const anyPct = pct(stats.anyDisability, stats.pop);
  const povertyPct = stats.disabilityTotal > 0 ? pct(stats.disabilityPoverty, stats.disabilityTotal) : null;

  return (
    <div className="space-y-4">
      {/* Key metrics */}
      <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 mb-2">
        <StatCallout
          value={anyPct !== null ? formatPercent(anyPct) : 'N/A'}
          label="with a disability"
          sub="any type"
          rateStyles={anyPct !== null ? rateStyle(anyPct) : { color: C.muted, background: C.limestone }}
        />
        <StatCallout
          value={stats.pop.toLocaleString()}
          label="total population"
          sub="civilian, non-institutionalized"
        />
        <StatCallout
          value={povertyPct !== null ? formatPercent(povertyPct) : 'N/A'}
          label="disabled + below poverty"
          sub="federal poverty level"
          rateStyles={povertyPct !== null && povertyPct > 25
            ? { color: C.brick, background: C.brickLight }
            : undefined}
        />
      </div>

      {/* By disability type */}
      <DataCard
        title="Disability Types — Population Breakdown"
        attribution={{ datasetName: 'ACS 5-Year 2022 — B18102–B18107', lastUpdated: null, uid: 'census-acs' }}
      >
        <div className="mb-3 text-xs rounded p-2" style={{ color: C.muted, background: C.limestone }}>
          People may have more than one disability type; totals may exceed the "any disability" count.
          ACS data is survey-based — small neighborhoods have wider margins of error.
        </div>
        {statRow('Any disability', anyPct !== null ? formatPercent(anyPct) : 'N/A', `~${stats.anyDisability.toLocaleString()} people`)}
        {statRow('Ambulatory (mobility) difficulty', pct(stats.ambulatory, stats.pop) !== null ? formatPercent(pct(stats.ambulatory, stats.pop)!) : 'N/A', `~${stats.ambulatory.toLocaleString()} people`)}
        {statRow('Cognitive difficulty', pct(stats.cognitive, stats.pop) !== null ? formatPercent(pct(stats.cognitive, stats.pop)!) : 'N/A', `~${stats.cognitive.toLocaleString()} people`)}
        {statRow('Independent living difficulty', pct(stats.independentLiving, stats.pop) !== null ? formatPercent(pct(stats.independentLiving, stats.pop)!) : 'N/A', `~${stats.independentLiving.toLocaleString()} people`)}
        {statRow('Self-care difficulty', pct(stats.selfCare, stats.pop) !== null ? formatPercent(pct(stats.selfCare, stats.pop)!) : 'N/A', `~${stats.selfCare.toLocaleString()} people`)}
        {statRow('Hearing difficulty', pct(stats.hearing, stats.pop) !== null ? formatPercent(pct(stats.hearing, stats.pop)!) : 'N/A', `~${stats.hearing.toLocaleString()} people`)}
        {statRow('Vision difficulty', pct(stats.vision, stats.pop) !== null ? formatPercent(pct(stats.vision, stats.pop)!) : 'N/A', `~${stats.vision.toLocaleString()} people`)}
      </DataCard>

      {/* Poverty crosswalk */}
      <DataCard
        title="Economic Vulnerability"
        attribution={{ datasetName: 'ACS 5-Year 2022 — C18130', lastUpdated: null }}
      >
        <p className="text-sm mb-3" style={{ color: C.muted }}>
          People with disabilities face significantly higher rates of poverty nationwide.
          This section shows the intersection in {neighborhood}.
        </p>
        {statRow(
          'Disabled residents below poverty line',
          povertyPct !== null ? formatPercent(povertyPct) : 'N/A',
          'As a share of all residents with a disability'
        )}
        <div
          className="mt-3 text-xs rounded p-2"
          style={{ color: C.muted, background: C.limestone, border: `1px solid ${C.rule}` }}
        >
          For reference: the national disability poverty rate is approximately 25–28% (ACS 2022).
          Rates above 30% indicate concentrated economic hardship in this community.
        </div>
      </DataCard>
    </div>
  );
}

function MobilityView({
  stats,
  neighborhood,
}: {
  stats: NeighborhoodDisabilityStats | null;
  neighborhood: string;
}) {
  const ambulatoryPct = stats ? pct(stats.ambulatory, stats.pop) : null;

  return (
    <div className="space-y-4">
      {/* Key metric */}
      {stats && (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <StatCallout
            value={ambulatoryPct !== null ? formatPercent(ambulatoryPct) : 'N/A'}
            label="ambulatory difficulty"
            sub="mobility impairment — ACS B18105"
            rateStyles={ambulatoryPct !== null ? rateStyle(ambulatoryPct) : { color: C.muted, background: C.limestone }}
          />
          <StatCallout
            value={stats.ambulatory.toLocaleString()}
            label="residents with mobility limitations"
            sub="civilian non-institutionalized"
          />
        </div>
      )}

      {!stats && (
        <div
          className="rounded-md p-3 text-sm"
          style={{ background: C.limestone, border: `1px solid ${C.rule}`, color: C.ochre }}
        >
          Census mobility data will appear here after running{' '}
          <code className="px-1 rounded" style={{ background: C.rule }}>scripts/build_disability.py</code>.
        </div>
      )}

      {/* ADA paratransit */}
      <ParatransitCard neighborhood={neighborhood} />

      {/* OSM infrastructure — future */}
      <DataCard title="Pedestrian Infrastructure (Coming Soon)">
        <div className="text-sm space-y-2" style={{ color: C.muted }}>
          <p>
            We are working to integrate <strong>OpenStreetMap</strong> data on curb cuts,
            wheelchair-accessible paths, and accessible parking in Cincinnati.
          </p>
          <p>
            OpenStreetMap is community-maintained — mapping quality varies by neighborhood.
            Well-mapped areas may appear more accessible simply because more volunteers have
            documented them. We will make this caveat prominent when the data is live.
          </p>
          <div className="flex gap-3 flex-wrap mt-3 text-xs">
            <a
              href="https://www.openstreetmap.org/#map=13/39.1031/-84.5120"
              target="_blank"
              rel="noopener noreferrer"
              className="underline"
              style={{ color: C.river }}
            >
              Help map Cincinnati accessibility on OSM →
            </a>
          </div>
        </div>
      </DataCard>

      {/* CMS care facilities — future */}
      <DataCard title="Nearby Care & Support Facilities (Coming Soon)">
        <div className="text-sm space-y-2" style={{ color: C.muted }}>
          <p>
            This section will show <strong>nursing homes, home health agencies, and rehabilitation
            facilities</strong> near {neighborhood} using CMS Care Compare data — a free federal
            dataset with quality ratings.
          </p>
          <a
            href="https://www.medicare.gov/care-compare/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-xs underline"
            style={{ color: C.river }}
          >
            View CMS Care Compare directly →
          </a>
        </div>
      </DataCard>
    </div>
  );
}

function VisionView({ stats }: { stats: NeighborhoodDisabilityStats | null }) {
  const visionPct = stats ? pct(stats.vision, stats.pop) : null;

  return (
    <div className="space-y-4">
      {stats && (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <StatCallout
            value={visionPct !== null ? formatPercent(visionPct) : 'N/A'}
            label="vision difficulty"
            sub="ACS B18103"
            rateStyles={visionPct !== null ? rateStyle(visionPct) : { color: C.muted, background: C.limestone }}
          />
          <StatCallout
            value={stats.vision.toLocaleString()}
            label="residents with vision impairment"
          />
        </div>
      )}

      {!stats && (
        <div
          className="rounded-md p-3 text-sm"
          style={{ background: C.limestone, border: `1px solid ${C.rule}`, color: C.ochre }}
        >
          Census vision data will appear here after running{' '}
          <code className="px-1 rounded" style={{ background: C.rule }}>scripts/build_disability.py</code>.
        </div>
      )}

      <DataCard title="Accessible Pedestrian Signals & Tactile Infrastructure (Coming Soon)">
        <div className="text-sm space-y-2" style={{ color: C.muted }}>
          <p>
            Audible pedestrian signals (APS) and tactile detectable warning surfaces are critical
            infrastructure for blind and low-vision residents. Cincinnati does not yet publish an
            open inventory of these installations.
          </p>
          <p>
            OpenStreetMap community tagging (<code>tactile_paving=yes</code>,{' '}
            <code>traffic_signals:sound=yes</code>) can partially fill this gap.
          </p>
        </div>
      </DataCard>

      <DataCard title="Local Vision Support Organizations">
        <div className="text-sm space-y-3" style={{ color: C.ink }}>
          {[
            {
              name: 'Cincinnati Association for the Blind and Visually Impaired (CABVI)',
              url: 'https://www.cabvi.org',
              desc: 'Provides rehabilitation, employment, and community services for people who are blind or have low vision in the Cincinnati region.',
            },
            {
              name: 'Ohio Library for the Blind and Print Disabled (via OPLIN)',
              url: 'https://library.ohio.gov/services-for-libraries/library-programs-development/accessible-reading/',
              desc: 'Free talking books, braille, and accessible formats for Ohioans who cannot read standard print.',
            },
          ].map((org) => (
            <div key={org.name} className="rounded p-3" style={{ border: `1px solid ${C.rule}` }}>
              <a
                href={org.url}
                target="_blank"
                rel="noopener noreferrer"
                className="font-medium text-sm underline"
                style={{ color: C.river }}
              >
                {org.name}
              </a>
              <p className="text-xs mt-1" style={{ color: C.muted }}>{org.desc}</p>
            </div>
          ))}
        </div>
      </DataCard>
    </div>
  );
}

function HearingView({ stats }: { stats: NeighborhoodDisabilityStats | null }) {
  const hearingPct = stats ? pct(stats.hearing, stats.pop) : null;

  return (
    <div className="space-y-4">
      {stats && (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <StatCallout
            value={hearingPct !== null ? formatPercent(hearingPct) : 'N/A'}
            label="hearing difficulty"
            sub="ACS B18102"
            rateStyles={hearingPct !== null ? rateStyle(hearingPct) : { color: C.muted, background: C.limestone }}
          />
          <StatCallout
            value={stats.hearing.toLocaleString()}
            label="residents with hearing impairment"
          />
        </div>
      )}

      {!stats && (
        <div
          className="rounded-md p-3 text-sm"
          style={{ background: C.limestone, border: `1px solid ${C.rule}`, color: C.ochre }}
        >
          Census hearing data will appear here after running{' '}
          <code className="px-1 rounded" style={{ background: C.rule }}>scripts/build_disability.py</code>.
        </div>
      )}

      <DataCard title="Public Communication Infrastructure">
        <div className="text-sm space-y-2" style={{ color: C.muted }}>
          <p>
            Visual alert systems, TTY/TDD availability at government offices, and ASL interpretation
            at public meetings are important for Deaf and hard-of-hearing residents. Cincinnati does
            not currently publish this as open data.
          </p>
          <p>
            The ADA requires city services to provide effective communication access on request.
            If you have encountered a barrier, you can file a complaint with the{' '}
            <a
              href="https://www.cincinnati-oh.gov/ada/"
              target="_blank"
              rel="noopener noreferrer"
              className="underline"
              style={{ color: C.river }}
            >
              City of Cincinnati ADA Coordinator
            </a>.
          </p>
        </div>
      </DataCard>

      <DataCard title="Local Deaf & Hard-of-Hearing Organizations">
        <div className="text-sm space-y-3" style={{ color: C.ink }}>
          {[
            {
              name: 'Hearing, Speech & Deaf Center of Greater Cincinnati',
              url: 'https://www.hsdcgc.org',
              desc: 'Provides audiological, speech-language, and Deaf services across the Greater Cincinnati region.',
            },
            {
              name: 'Ohio School for the Deaf Alumni Association',
              url: 'https://www.ohioschoolforthedeaf.org',
              desc: 'Community connection and advocacy for the Deaf community in Ohio.',
            },
          ].map((org) => (
            <div key={org.name} className="rounded p-3" style={{ border: `1px solid ${C.rule}` }}>
              <a
                href={org.url}
                target="_blank"
                rel="noopener noreferrer"
                className="font-medium text-sm underline"
                style={{ color: C.river }}
              >
                {org.name}
              </a>
              <p className="text-xs mt-1" style={{ color: C.muted }}>{org.desc}</p>
            </div>
          ))}
        </div>
      </DataCard>
    </div>
  );
}

function CognitiveView({ stats }: { stats: NeighborhoodDisabilityStats | null }) {
  const cognitivePct = stats ? pct(stats.cognitive, stats.pop) : null;
  const independentPct = stats ? pct(stats.independentLiving, stats.pop) : null;

  return (
    <div className="space-y-4">
      {stats && (
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          <StatCallout
            value={cognitivePct !== null ? formatPercent(cognitivePct) : 'N/A'}
            label="cognitive difficulty"
            sub="ACS B18104"
            rateStyles={cognitivePct !== null ? rateStyle(cognitivePct) : { color: C.muted, background: C.limestone }}
          />
          <StatCallout
            value={independentPct !== null ? formatPercent(independentPct) : 'N/A'}
            label="independent living difficulty"
            sub="ACS B18107"
            rateStyles={independentPct !== null ? rateStyle(independentPct) : { color: C.muted, background: C.limestone }}
          />
          <StatCallout
            value={stats ? pct(stats.selfCare, stats.pop) !== null ? formatPercent(pct(stats.selfCare, stats.pop)!) : 'N/A' : 'N/A'}
            label="self-care difficulty"
            sub="ACS B18106"
          />
        </div>
      )}

      {!stats && (
        <div
          className="rounded-md p-3 text-sm"
          style={{ background: C.limestone, border: `1px solid ${C.rule}`, color: C.ochre }}
        >
          Census cognitive data will appear here after running{' '}
          <code className="px-1 rounded" style={{ background: C.rule }}>scripts/build_disability.py</code>.
        </div>
      )}

      <DataCard title="Mental Health & Developmental Disability Services">
        <div className="text-sm space-y-2" style={{ color: C.muted }}>
          <p>
            This section will show nearby <strong>community mental health centers, supported living
            facilities, and developmental disability service providers</strong> when those datasets
            become available as open data.
          </p>
          <div className="mt-3 space-y-2">
            <p className="font-medium text-xs" style={{ color: C.ink }}>Available now:</p>
            {[
              {
                label: 'ADAMHS Board of Hamilton County — Community mental health services directory',
                href: 'https://www.adamhs.org/finding-help/',
              },
              {
                label: 'Ohio Department of Developmental Disabilities — County board locator',
                href: 'https://dodd.ohio.gov/county-boards',
              },
              {
                label: 'Hamilton County DD Services',
                href: 'https://hcdd.org',
              },
            ].map((r) => (
              <a
                key={r.href}
                href={r.href}
                target="_blank"
                rel="noopener noreferrer"
                className="block text-xs underline"
                style={{ color: C.river }}
              >
                {r.label} →
              </a>
            ))}
          </div>
        </div>
      </DataCard>
    </div>
  );
}

// ── Main component ────────────────────────────────────────────────────────────

export default function Accessibility() {
  useTranslation(); // keep i18n context available for future string keys
  const [selectedNeighborhood, setSelectedNeighborhood] = useState<string>(NEIGHBORHOODS[0]);
  const [activeView, setActiveView] = useState<ImpairmentView>('overview');
  const [disabilityMap, setDisabilityMap] = useState<Map<string, NeighborhoodDisabilityStats>>(new Map());
  const [loadingStats, setLoadingStats] = useState(true);
  const [statsError, setStatsError] = useState<string | null>(null);

  // Load disability stats once on mount
  useEffect(() => {
    setLoadingStats(true);
    fetchNeighborhoodDisabilityStats()
      .then(setDisabilityMap)
      .catch((e) => setStatsError(String(e)))
      .finally(() => setLoadingStats(false));
  }, []);

  const stats = useMemo((): NeighborhoodDisabilityStats | null => {
    if (loadingStats || disabilityMap.size === 0) return null;
    const key = stripNeighborhoodName(selectedNeighborhood);
    return disabilityMap.get(key) ?? null;
  }, [disabilityMap, selectedNeighborhood, loadingStats]);

  return (
    <div className="space-y-6">
      {/* Page header */}
      <div>
        <h1 className="text-2xl font-bold" style={{ color: C.riverDeep }}>Disability Access Resource Center</h1>
        <p className="mt-1 text-sm" style={{ color: C.muted }}>
          Disability demographics, transit coverage, and infrastructure data for Cincinnati neighborhoods.
          Use the impairment type selector to focus on what matters to you.
        </p>
      </div>

      {/* Data scarcity banner */}
      <div
        className="rounded-md p-4 flex items-start gap-3"
        style={{ background: C.limestone, border: `1px solid ${C.rule}` }}
      >
        <span className="shrink-0 mt-0.5" style={{ color: C.ochre }}>
          <IconWarning />
        </span>
        <div>
          <p className="text-sm font-semibold mb-1" style={{ color: C.ochre }}>This section has limited data — and that's part of the story</p>
          <p className="text-sm leading-relaxed" style={{ color: C.muted }}>
            Cincinnati does not publish most disability-related infrastructure data as open data — no curb-cut
            inventory, no audible pedestrian signal map, no accessible parking enforcement records. What you see
            here is drawn from U.S. Census ACS demographics and SORTA's bus stop network. The gaps are documented
            below in each view's <strong>"This data should be public"</strong> section, with specific agencies
            you can contact to request it.
          </p>
        </div>
      </div>

      {/* Controls: neighborhood + view selector */}
      <div
        className="bg-white rounded-md shadow-sm p-4 space-y-4"
        style={{ border: `1px solid ${C.rule}` }}
      >
        {/* Neighborhood selector */}
        <div className="flex flex-col sm:flex-row gap-3 items-start sm:items-center">
          <label htmlFor="acc-neighborhood" className="text-sm font-medium shrink-0" style={{ color: C.ink }}>
            Neighborhood
          </label>
          <select
            id="acc-neighborhood"
            value={selectedNeighborhood}
            onChange={(e) => setSelectedNeighborhood(e.target.value)}
            className="w-full sm:w-auto rounded-md px-3 py-2 text-sm focus:outline-none bg-white"
            style={{ border: `1px solid ${C.rule}`, color: C.ink }}
          >
            {NEIGHBORHOODS.map((n) => (
              <option key={n} value={n}>{n}</option>
            ))}
          </select>
          {loadingStats && (
            <span className="text-xs animate-pulse" style={{ color: C.muted }}>Loading disability data…</span>
          )}
          {statsError && (
            <span className="text-xs" style={{ color: C.brick }}>{statsError}</span>
          )}
        </div>

        {/* Impairment view pills */}
        <div>
          <p className="text-xs font-medium mb-2" style={{ color: C.muted }}>View by impairment type</p>
          <div className="flex flex-wrap gap-2">
            {VIEWS.map((view) => (
              <button
                key={view.id}
                onClick={() => setActiveView(view.id)}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-full text-sm font-medium transition-colors"
                style={activeView === view.id
                  ? { background: C.riverDeep, color: '#fff', border: `1px solid ${C.riverDeep}` }
                  : { background: '#fff', color: C.ink, border: `1px solid ${C.rule}` }
                }
                title={view.description}
              >
                <span>{view.icon}</span>
                <span>{view.label}</span>
              </button>
            ))}
          </div>
          <p className="text-xs mt-2 italic" style={{ color: C.muted }}>
            {VIEWS.find((v) => v.id === activeView)?.description}
          </p>
        </div>
      </div>

      {/* Active view content */}
      <div>
        {activeView === 'overview' && (
          <OverviewView stats={stats} neighborhood={selectedNeighborhood} />
        )}
        {activeView === 'mobility' && (
          <MobilityView stats={stats} neighborhood={selectedNeighborhood} />
        )}
        {activeView === 'vision' && (
          <VisionView stats={stats} />
        )}
        {activeView === 'hearing' && (
          <HearingView stats={stats} />
        )}
        {activeView === 'cognitive' && (
          <CognitiveView stats={stats} />
        )}
      </div>

      {/* Data gaps call to action — always shown at bottom */}
      <DataGapsCard view={activeView} />

      {/* ACS data note */}
      <div
        className="text-xs rounded-md p-3 space-y-1"
        style={{ color: C.muted, background: C.limestone }}
      >
        <p className="font-medium" style={{ color: C.ink }}>About this data</p>
        <p>
          Disability statistics are from the <strong>U.S. Census American Community Survey
          5-Year estimates (2022)</strong>, table series B18101–B18107 and C18130.
          ACS data is survey-based — estimates for small neighborhoods carry wider margins of error.
          Neighborhood boundaries use Cincinnati's Statistical Neighborhood Approximations (SNAs);
          census tract boundaries don't align perfectly and some ambiguous tracts are attributed
          to their nearest neighborhood centroid.
        </p>
        <p>
          <a
            href="https://www.census.gov/programs-surveys/acs/data.html"
            target="_blank"
            rel="noopener noreferrer"
            className="underline"
            style={{ color: C.river }}
          >
            U.S. Census ACS →
          </a>
          {' · '}
          <a
            href="https://censusreporter.org/tables/B18101/"
            target="_blank"
            rel="noopener noreferrer"
            className="underline"
            style={{ color: C.river }}
          >
            Explore disability tables on Census Reporter →
          </a>
        </p>
      </div>
    </div>
  );
}
