// ─── App-level ───────────────────────────────────────────────────────────────

export type TabId = 'address' | 'neighborhood' | 'police' | 'explorer' | 'roadmap' | 'displacement' | 'owner' | 'accessibility' | 'lead';
export type Language = 'en' | 'es';

// ─── SODA API ────────────────────────────────────────────────────────────────

export interface SODAQueryParams {
  $where?: string;
  $select?: string;
  $limit?: number;
  $offset?: number;
  $order?: string;
  $group?: string;
  [key: string]: string | number | undefined;
}

// ─── CRIME ───────────────────────────────────────────────────────────────────

export interface CrimeIncident {
  date_reported?: string;
  datereported?: string; // STARS dataset field name
  offense: string;
  neighborhood: string;
  latitude?: string;
  longitude?: string;
}

// ─── PERMITS ─────────────────────────────────────────────────────────────────

export interface BuildingPermit {
  applieddate: string;
  permittype: string;
  address: string;
  neighborhood: string;
  worktype?: string;
  companyname?: string;
}

// ─── INSPECTIONS ─────────────────────────────────────────────────────────────

export interface Inspection {
  inspecdate: string;
  inspecresult: string;
  address: string;
  neighborhood?: string;
  inspectiontype?: string;
}

// ─── FOOD SAFETY ─────────────────────────────────────────────────────────────

export interface FoodViolation {
  inspection_date: string;
  facility_name: string;
  address: string;
  violation?: string;
  neighborhood?: string;
}

// ─── TAX ABATEMENT ───────────────────────────────────────────────────────────

export interface TaxAbatement {
  address: string;
  neighborhood: string;
  incentive_amount?: string;
  tax_abatement_type?: string;
}

// ─── PLAP ────────────────────────────────────────────────────────────────────

export interface PLAPRecord {
  date: string;
  address: string;
  neighborhood: string;
}

// ─── POLICE ──────────────────────────────────────────────────────────────────

export interface TrafficStop {
  interview_date: string; // actual API field name
  race: string;
  gender: string;
  action_taken: string;
  district: string;
}

export interface PedestrianStop {
  interview_date: string; // actual API field name
  race: string;
  gender: string;
  action_taken: string;
  district?: string;
}

export interface UseOfForce {
  date_of_incident: string;
  address: string;
  neighborhood: string;
  unique_report_id?: string;
}

export interface OISIncident {
  date: string;
  address: string;
  neighborhood: string;
}

// ─── FIRE / EMS ──────────────────────────────────────────────────────────────

export interface FireEMSIncident {
  create_time: string;
  incident_type: string;
  neighborhood: string;
}

// ─── ADDRESS LOOKUP ───────────────────────────────────────────────────────────

export interface GeocodedAddress {
  formatted: string;
  lat: number;
  lng: number;
  street: string;
  neighborhood?: string;
}

export interface SORTAStop {
  stop_id: string;
  stop_name: string;
  stop_lat: number;
  stop_lon: number;
  routes: string[];
}

// ─── OHGO TRAFFIC ────────────────────────────────────────────────────────────

export interface OHGOIncident {
  id: string;
  lat: number;
  lng: number;
  location: string;
  description: string;
  category: string;
  routeName: string;
  roadStatus: string;
}

export interface OHGOCamera {
  id: string;
  lat: number;
  lng: number;
  location: string;
  description: string;
  views: Array<{
    direction: string;
    smallUrl: string;
    largeUrl: string;
    mainRoute: string;
  }>;
}

export interface OHGOConstruction {
  id: string;
  lat: number;
  lng: number;
  location: string;
  description: string;
  routeName: string;
}

// ─── COMMUNITY PERCEPTIONS ───────────────────────────────────────────────────

export interface PerceptionRecord {
  question: string;
  neighborhood: string;
  response: string;
}

// ─── ACCESSIBILITY ───────────────────────────────────────────────────────────

/**
 * Pre-computed disability statistics for a single Cincinnati neighborhood.
 * Generated by scripts/build_disability.py from ACS 5-Year 2022 data.
 * All counts are civilian noninstitutionalized population.
 */
export interface NeighborhoodDisabilityStats {
  name: string;
  /** Total civilian noninstitutionalized population */
  pop: number;
  /** Count with any disability (1+ types) — from C18108 */
  anyDisability: number;
  /** Hearing difficulty count — from B18102 */
  hearing: number;
  /** Vision difficulty count — from B18103 */
  vision: number;
  /** Cognitive difficulty count — from B18104 */
  cognitive: number;
  /** Ambulatory (mobility) difficulty count — from B18105 */
  ambulatory: number;
  /** Self-care difficulty count — from B18106 */
  selfCare: number;
  /** Independent living difficulty count — from B18107 */
  independentLiving: number;
  /** Total with a disability (C18130 denominator) */
  disabilityTotal: number;
  /** With a disability AND income below federal poverty level — from C18130 */
  disabilityPoverty: number;
}

// ─── NEIGHBORHOOD EXPLORER ───────────────────────────────────────────────────

export type DimensionId =
  | 'affordability'
  | 'income'
  | 'safety'
  | 'transit'
  | 'investment'
  | 'blight'
  | 'parks'     // CAGIS: park acreage per 1,000 residents within 0.75 mi of centroid
  | 'flood'     // FEMA NFHL: whether centroid falls in a Special Flood Hazard Area
  | 'food'      // USDA FARA 2019: % of neighborhood population in a food desert tract
  | 'ej'        // EPA EJScreen 2023: composite air toxics + diesel + Superfund + traffic burden
  | 'schools';

export interface Dimension {
  id: DimensionId;
  labelKey: string;
  descriptionKey: string;
  methodology?: string;  // Plain-English explanation of how the score is computed
  enabled: boolean;
  weight: number;        // 1–5
  available: boolean;    // false = disabled (schools)
  higherIsBetter: boolean;
  incomeSub?: 'higher' | 'lower';
}

export interface NeighborhoodRawMetrics {
  // Affordability
  rentBurdenRate?: number;
  medianGrossRent?: number;
  rentBurdenMOE?: number;
  // Income
  medianHouseholdIncome?: number;
  incomeMOE?: number;
  // Safety
  crimeRatePer1000?: number;
  crimeCount?: number;
  // Transit
  uniqueRouteCount?: number;
  stopCount?: number;
  // Investment
  permitYoYChange?: number;
  recentPermitCount?: number;
  // Blight
  plapPerSqMile?: number;
  firstPassRate?: number;
  // Parks (CAGIS) — acreage within 0.75 mi of neighborhood centroid / pop * 1000
  parkAcresPer1000?: number;
  parkTotalAcres?: number;
  // Flood (FEMA NFHL) — true if centroid is in a Special Flood Hazard Area
  inFloodZone?: boolean;
  // Food Access (USDA FARA 2019) — % of neighborhood population in a LILA food desert tract
  foodDesertPct?: number;     // 0–100; higher = more food desert exposure
  povertyRate?: number;       // weighted average poverty rate across tracts
  medianFamilyIncomeFARA?: number;
  // Population (denominator)
  population?: number;
  // Environmental Justice (EPA EJScreen 2023)
  // National percentile ranks — 0 (least exposed nationally) to 100 (most exposed).
  // ejPollutionIndex is a weighted composite; all individual fields are percentiles.
  ejPollutionIndex?: number;     // composite pollution burden (higher = worse)
  ejCancerPctile?: number;       // air toxics lifetime cancer risk %ile
  ejDieselPctile?: number;       // diesel particulate matter %ile
  ejTrafficPctile?: number;      // traffic proximity %ile
  ejSuperfundPctile?: number;    // Superfund site proximity %ile
  ejWastePctile?: number;        // hazardous waste facility proximity %ile
  ejWastewaterPctile?: number;   // wastewater discharge %ile
  ejPm25Pctile?: number;         // PM 2.5 annual average %ile
}

export interface NeighborhoodScore {
  name: string;
  compositeScore: number;
  dimensionScores: Record<DimensionId, number | null>;
  rawMetrics: NeighborhoodRawMetrics;
  hasInsufficientData: boolean;
}

// ─── LEAD SERVICE LINES ───────────────────────────────────────────────────────

/**
 * Pre-computed lead service line inventory for a single Cincinnati neighborhood.
 * Generated by scripts/build_lead.py from GCWW open data.
 *
 * "Lead or unknown" = lines that may still be exposing residents to lead;
 * these are the civic urgency metric.
 */
export interface NeighborhoodLeadStats {
  /** Neighborhood name (matches SNA list) */
  name: string;
  /** Total service lines in inventory for this neighborhood */
  total: number;
  /** Lines confirmed as lead material */
  lead: number;
  /** Lines with unknown material (assumed risky until confirmed) */
  unknown: number;
  /** Lines confirmed galvanized (corrosion concern, often paired with lead) */
  galvanized: number;
  /** Lines confirmed as copper or other non-lead material */
  copper: number;
  /** Lines already replaced (private-side) */
  replaced: number;
  /** Last time this data was pulled from GCWW */
  asOf?: string;
}

// ─── AIR TOXICS / ENVIRONMENTAL JUSTICE ──────────────────────────────────────

/**
 * Pre-computed EPA AirToxScreen 2019 air toxics indicators per neighborhood.
 * Generated by scripts/build_ejscreen.py, which queries the EPA's ArcGIS
 * feature service (still live 2026-03-28):
 *   Cancer_risk_per_million_due_to_cumulative_air_toxics / FeatureServer/0
 *
 * This is the same underlying data EJScreen uses for its CANCER and DSLPM
 * indicators. EJScreen's REST API went offline Feb 2025; this service is live.
 *
 * ejIndex = TOTAL_RISK (cumulative air toxics cancer risk, cases per million).
 * Higher ejIndex = greater air toxics burden = lower Explorer score
 * (the Explorer dimension uses higherIsBetter: false).
 */
export interface NeighborhoodEJStats {
  name: string;
  // Primary scoring metric — maps to ejPollutionIndex in NeighborhoodRawMetrics
  ejIndex: number | null;          // cumulative air toxics cancer risk (cases per million)
  // Supporting indicators (available for detail display)
  dieselPm?: number | null;        // diesel PM ambient concentration (µg/m³)
  respiratoryHI?: number | null;   // respiratory hazard index
  // Legacy percentile fields — null when built from AirToxScreen source
  cancerPctile?: number | null;
  dieselPctile?: number | null;
  trafficPctile?: number | null;
  superfundPctile?: number | null;
  wastePctile?: number | null;
  wastewaterPctile?: number | null;
  pm25Pctile?: number | null;
  tractCount: number;
  pop: number;
  source?: string;   // 'airtoxscreen_2019' | 'ejscreen_2023'
  asOf?: string;
}
